shogun-toolbox/shogun

tests/unit/regression/LibSVR_unittest.cc
#2638 @iglesias Please review.
=> Remove redundant labels_test/lab_test in LibSVR_unittest

src/shogun/lib/SGVector.cpp, src/shogun/lib/SGVector.h
=> Remove SGVector::fequal

src/shogun/mathematics/Math.cpp, src/shogun/mathematics/Math.h, src/shogun/mathematics/Statistics.h, src/shogun/mathematics/ajd/JADiagOrth.cpp
The warnings are mainly due to documentation and swig. I will push more commits here.
=> Remove warnings in deb3 build.

src/shogun/mathematics/linalg/internal/implementation/Convolve.h, src/shogun/mathematics/linalg/internal/modules/Core.h, tests/unit/mathematics/linalg/Convolve_unittest.cc
@lisitsyn, @vigsterkr Pushed #2418 again, this time against the develop branch instead of feature/linalg
=> added convolution to linalg

src/interfaces/modular/IO.i, src/interfaces/modular/IO_includes.i, src/shogun/io/NeuralNetworkFileReader.cpp, src/shogun/io/NeuralNetworkFileReader.h, src/shogun/neuralnets/NeuralLayer.h, src/shogun/neuralnets/NeuralNetwork.h, tests/unit/io/NeuralNetworkFileReader_unittest.cc
=> added support for configuring neural networks using JSON files

src/shogun/mathematics/linalg/internal/implementation/Dot.h, src/shogun/mathematics/linalg/internal/modules/Core.h, src/shogun/mathematics/linalg/internal/modules/Redux.h, src/shogun/mathematics/linalg/internal/modules/SpecialPurpose.h, src/shogun/mathematics/linalg/internal/modules/Util.h, src/shogun/mathematics/linalg/linalg.h, tests/unit/mathematics/linalg/DotProduct_unittest.cc
Addresses the basics for issue #2667 and #2582
=> Added Shogun's native dot impl to linalg under NATIVE backend

examples/undocumented/libshogun/preprocessor_fisherlda.cpp, examples/undocumented/libshogun/streaming_onlineliblinear_sparse.cpp, examples/undocumented/python_modular/preprocessor_fisherlda_modular.py, src/shogun/machine/gp/SoftMaxLikelihood.cpp, src/shogun/machine/gp/SoftMaxLikelihood.h, src/shogun/preprocessor/BAHSIC.cpp, src/shogun/preprocessor/BAHSIC.h, src/shogun/preprocessor/DimensionReductionPreprocessor.cpp, src/shogun/preprocessor/DimensionReductionPreprocessor.h, src/shogun/preprocessor/FeatureSelection.cpp, src/shogun/preprocessor/FeatureSelection.h, src/shogun/preprocessor/FisherLDA.cpp, src/shogun/preprocessor/FisherLDA.h, src/shogun/preprocessor/KernelDependenceMaximization.cpp, src/shogun/preprocessor/KernelDependenceMaximization.h, src/shogun/regression/LeastAngleRegression.cpp, tests/unit/preprocessor/FisherLDA_unittest.cc
Removes annoying warnings that appear when using clang on macosx yosemite
=> Removed some warning causes

src/shogun/converter/Isomap.h
I added some documentation to the Isomap doxygen class as required by issue #2673 .
I mostly recycled it from here: http://tapkee.lisitsyn.me/ .
I also added the wikipedia link as required in the issue.
Is there anything else I can add in this documentation that would be helpful?
=> added documentation for Isomap doxygen class

src/shogun/mathematics/linalg/internal/implementation/Add.h, src/shogun/mathematics/linalg/internal/implementation/Sum.h, tests/unit/mathematics/linalg/Add_unittest.cc
@lambday @iglesias Please review.
=> Add native implementation for addition of vectors and matrices in linalg

src/shogun/converter/FactorAnalysis.h
in reference to: #2673 
added documentation for the FactorAnalysis doxygen class mainly from here: http://tapkee.lisitsyn.me/
is there any other relevent info about Factor Analysis that i can add here?
=> added documentation for the FactorAnalysis class

src/shogun/base/some.h, tests/unit/base/Some_unittest.cc
=> Added some - a shared_ptr wrapper

src/shogun/mathematics/Random.h
inline "int64_t random_s64() const", too and a small cleanup.
=> inline "int64_t random_s64() const"

src/shogun/lib/SGVector.cpp
Fix issue #2702 in file src/shogun/lib/SGVector.cpp
=> shogun:lib Replace ASSERT with REQUIRE

src/shogun/mathematics/linalg/internal/implementation/Add.h, tests/unit/mathematics/linalg/Add_unittest.cc
@lambday I added openmp. Not sure about it, can be incorrect.
=> Add openmp and default values in function add(linalg)

src/shogun/mathematics/linalg/internal/implementation/VectorSum.h, tests/unit/mathematics/linalg/VectorSum_unittest.cc
=> added native implementation for sum of vector in linalg

src/shogun/kernel/GaussianARDKernel.h, src/shogun/kernel/GaussianKernel.h, src/shogun/kernel/LinearARDKernel.cpp, src/shogun/kernel/LinearARDKernel.h, src/shogun/machine/gp/GaussianARDFITCKernel.cpp, src/shogun/machine/gp/GaussianARDFITCKernel.h
=> add a kernel to support FITC inference

src/shogun/base/unique.h, src/shogun/transfer/multitask/MultitaskL12LogisticRegression.cpp, src/shogun/transfer/multitask/MultitaskL12LogisticRegression.h, tests/unit/base/Unique_unittest.cc, tests/unit/base/Unique_unittest.h
This thing was described in #2564
=> Added Unique handler to store implementations

doc/pages/Methods.mainpage
Have updated the *completed*  **features**, **preprocesssors**, **kernels**, **distance measures** and **methods** based on the implementations found under respective directories in *src/shogun* instead of only the examples folder. Hope that is alright as it seemed to contain a more complete list than that in examples.
=> Issue #2730: Update Methods list [FIX]

src/shogun/kernel/GaussianARDKernel.cpp, src/shogun/kernel/GaussianARDKernel.h, src/shogun/kernel/LinearARDKernel.cpp, src/shogun/kernel/LinearARDKernel.h, src/shogun/machine/gp/GaussianARDFITCKernel.cpp, src/shogun/machine/gp/GaussianARDFITCKernel.h
=> minor fix in FITC kernels

tests/unit/lib/SGSparseMatrix_unittest.cc
=> Fixed compilation error in SGSparseMatrix unittet in absence of Eigen3

tests/unit/lib/SGSparseMatrix_unittest.cc
create a template to generate both sparse and dense matrix and made the rest of the test more concise. @iglesias
=> modified sparse matrix unit test, made it cleaner

src/shogun/machine/gp/FITCInferenceBase.cpp, src/shogun/machine/gp/FITCInferenceBase.h
=> add the base FITC class

src/shogun/machine/GaussianProcessMachine.cpp, src/shogun/machine/gp/FITCInferenceBase.cpp, src/shogun/machine/gp/FITCInferenceBase.h, src/shogun/machine/gp/FITCInferenceMethod.cpp, src/shogun/machine/gp/FITCInferenceMethod.h, src/shogun/machine/gp/GaussianARDFITCKernel.cpp, src/shogun/machine/gp/SingleFITCLaplacianBase.cpp, src/shogun/machine/gp/SingleFITCLaplacianBase.h, src/shogun/regression/GaussianProcessRegression.cpp
=> add the FITC framework2

examples/undocumented/libshogun/so_fg_multilabel.cpp, src/shogun/structure/FactorGraphDataGenerator.cpp, src/shogun/structure/FactorGraphDataGenerator.h, src/shogun/structure/GEMPLP.cpp, src/shogun/structure/GEMPLP.h, src/shogun/structure/MAPInference.cpp, src/shogun/structure/MAPInference.h, tests/unit/structure/BeliefPropagation_unittest.cc, tests/unit/structure/GEMPLP_unittest.cc, tests/unit/structure/GraphCut_unittest.cc
@hushell Could you please help me to check this patch?
=> added GEMPLP

src/interfaces/modular/GaussianProcess.i, src/interfaces/modular/GaussianProcess_includes.i, src/shogun/machine/GaussianProcessMachine.cpp, src/shogun/machine/gp/FITCInferenceMethod.cpp, src/shogun/machine/gp/FITCInferenceMethod.h, src/shogun/regression/GaussianProcessRegression.cpp, tests/unit/machine/gp/FITCInferenceMethod_unittest.cc, tests/unit/machine/gp/SingleFITCInferenceBase_unittest.cc, tests/unit/regression/GaussianProcessRegression_unittest.cc
@karlnapf 
take a look at this.
I will update the diagonal kernel stuff once PRs for FITC regression and FITC binary Laplace are merged.
=> refactor FITC regression

examples/undocumented/libshogun/neuralnets_basic.cpp, examples/undocumented/libshogun/neuralnets_convolutional.cpp, examples/undocumented/libshogun/neuralnets_deep_autoencoder.cpp, examples/undocumented/libshogun/neuralnets_deep_belief_network.cpp
fixed the uncaught exception pointed out in the coverity scans: https://gist.github.com/khalednasr/521446d352f0bf33b283
=> fixed uncought exception problem in neuralnets c++ examples

src/shogun/lib/SGMatrix.cpp, src/shogun/lib/SGSparseMatrix.h, tests/unit/lib/SGSparseMatrix_unittest.cc
corresponds to #2781 @karlnapf
=> additional PR to fix unsolved issue

src/shogun/machine/gp/LaplacianInferenceBase.cpp, src/shogun/machine/gp/LaplacianInferenceBase.h, src/shogun/machine/gp/MultiLaplacianInferenceMethod.cpp, src/shogun/machine/gp/MultiLaplacianInferenceMethod.h, src/shogun/machine/gp/SingleLaplacianInferenceMethod.cpp, src/shogun/machine/gp/SingleLaplacianInferenceMethod.h
=> make the laplace result consistent with regression

src/shogun/machine/gp/SingleFITCLaplacianInferenceMethod.cpp, src/shogun/machine/gp/SingleFITCLaplacianInferenceMethod.h, tests/unit/machine/gp/SingleFITCLaplacianInferenceMethod_unittest.cc
@karlnapf 
take a look at this.
=> add the FITC Laplace for binary classification using Newton's method

src/shogun/neuralnets/NeuralNetwork.cpp, tests/unit/neuralnets/NeuralNetwork_unittest.cc
=> added confidences to neural networks output

src/shogun/kernel/GaussianARDKernel.cpp, src/shogun/kernel/GaussianARDKernel.h, src/shogun/kernel/Kernel.h, src/shogun/machine/gp/GaussianARDFITCKernel.cpp, src/shogun/machine/gp/GaussianARDFITCKernel.h, tests/unit/kernel/GaussianARDKernel_unittest.cc, tests/unit/machine/gp/FITCInferenceMethod_unittest.cc
=> update the method for ARD kernels

src/shogun/lib/GPUMatrix.h, src/shogun/mathematics/linalg/internal/implementation/ElementwiseProduct.h, src/shogun/mathematics/linalg/internal/modules/Core.h, tests/unit/mathematics/linalg/ElementwiseProduct_unittest.cc
- Also Put `VCLMatrixBase CGPUMatrix::vcl_matrix()` under SWIG guard to avoid possible SWIG issue.
=> Added matrix-type independent elementwise-product in linalg

src/shogun/mathematics/linalg/internal/implementation/Add.h, src/shogun/mathematics/linalg/internal/modules/Core.h, tests/unit/mathematics/linalg/Add_unittest.cc
=> Added matrix-type independent add in linalg

src/shogun/machine/gp/SingleFITCLaplacianInferenceMethodWithLBFGS.cpp, src/shogun/machine/gp/SingleFITCLaplacianInferenceMethodWithLBFGS.h, tests/unit/machine/gp/SingleFITCLaplacianInferenceMethodWithLBFGS_unittest.cc
=> Fitc lbfgs

src/shogun/mathematics/linalg/internal/implementation/Apply.h, src/shogun/mathematics/linalg/internal/modules/Core.h, tests/unit/mathematics/linalg/Apply_unittest.cc
@karlnapf please have a look. This should be useful.
=> Added linalg::apply for matrix vector multiplication

src/shogun/kernel/GaussianARDKernel.cpp, src/shogun/kernel/LinearARDKernel.cpp, src/shogun/machine/gp/SingleFITCLaplacianInferenceMethod.cpp
@karlnapf 
let's see whether this PR can fix the error when viennaCL is used.
=> fix an error when viennaCL is used

src/interfaces/modular/Kernel.i, src/interfaces/modular/Kernel_includes.i, src/shogun/kernel/Kernel.cpp, src/shogun/kernel/Kernel.h, src/shogun/kernel/PeriodicKernel.cpp, src/shogun/kernel/PeriodicKernel.h, tests/unit/kernel/PeriodicKernel_unittest.cc
An implementation of the periodic kernel as described in [Kernel Cookbook](http://mlg.eng.cam.ac.uk/duvenaud/cookbook/index.html)
=> Added periodic kernel

src/shogun/modelselection/ParameterCombination.cpp
=> Fix parameter combination print for SGVectors

src/interfaces/modular/GaussianProcess.i, src/interfaces/modular/GaussianProcess_includes.i, src/shogun/classifier/GaussianProcessClassification.cpp, src/shogun/machine/GaussianProcessMachine.cpp, tests/unit/classifier/GaussianProcessClassification_unittest.cc
@karlnapf 
I will soon send PRs about the notebook and  the bug related to ViennaCL
=> Fitc laplace

src/shogun/kernel/GaussianARDKernel.cpp, src/shogun/kernel/GaussianARDKernel.h, src/shogun/kernel/LinearARDKernel.cpp, src/shogun/kernel/LinearARDKernel.h, src/shogun/machine/gp/GaussianARDFITCKernel.cpp, src/shogun/machine/gp/GaussianARDFITCKernel.h
=> fix a bug related to ViennaCL

src/shogun/modelselection/GradientModelSelection.cpp, src/shogun/modelselection/ParameterCombination.cpp
=> deal with matrix parameters in model selection

benchmarks/elementwise_benchmark.cpp, src/shogun/mathematics/linalg/internal/implementation/ElementwiseUnaryOperation.h, src/shogun/mathematics/linalg/internal/implementation/operations/Parameter.h, src/shogun/mathematics/linalg/internal/opencl_util.h, tests/unit/mathematics/linalg/ElementwiseOperations_unittest.cc
@karlnapf looks way much cleaner now, a la @lisitsyn.
=> Added a format method for OpenCL expressions in elementwise operations

src/interfaces/modular/Kernel.i, src/interfaces/modular/Kernel_includes.i, src/shogun/machine/GaussianProcessMachine.cpp, src/shogun/machine/gp/FITCInferenceBase.cpp, src/shogun/machine/gp/FITCInferenceBase.h, src/shogun/machine/gp/SingleFITCLaplacianBase.cpp, src/shogun/machine/gp/SingleFITCLaplacianBase.h, src/shogun/machine/gp/SingleFITCLaplacianInferenceMethod.cpp
=> Optimizing inducing points

src/shogun/machine/gp/SingleFITCLaplacianBase.cpp
=> fixed a bug in Coverity Scan

src/shogun/base/range.h, tests/unit/base/Range_unittest.cc
This PR adds a class and two helper functions to support python-like loops:
```cpp
for (auto i : range(elements.size())) { ... }
```
=> Add Range for beautiful for-loops

src/shogun/machine/gp/EPInferenceMethod.cpp, src/shogun/machine/gp/EPInferenceMethod.h, src/shogun/machine/gp/ExactInferenceMethod.cpp, src/shogun/machine/gp/ExactInferenceMethod.h, src/shogun/machine/gp/GaussianLikelihood.cpp, src/shogun/machine/gp/GaussianLikelihood.h, src/shogun/machine/gp/InferenceMethod.cpp, src/shogun/machine/gp/InferenceMethod.h, src/shogun/machine/gp/LikelihoodModel.cpp, src/shogun/machine/gp/LikelihoodModel.h, src/shogun/machine/gp/LogitLikelihood.cpp, src/shogun/machine/gp/LogitLikelihood.h, src/shogun/machine/gp/MeanFunction.h, src/shogun/machine/gp/ProbitLikelihood.cpp, src/shogun/machine/gp/ProbitLikelihood.h, src/shogun/machine/gp/SoftMaxLikelihood.cpp, src/shogun/machine/gp/SoftMaxLikelihood.h, src/shogun/machine/gp/StudentsTLikelihood.cpp, src/shogun/machine/gp/StudentsTLikelihood.h, src/shogun/machine/gp/ZeroMean.cpp, src/shogun/machine/gp/ZeroMean.h
=> change the license

src/shogun/features/DenseSubSamplesFeatures.cpp, src/shogun/features/DenseSubSamplesFeatures.h, src/shogun/features/Features.cpp, src/shogun/features/Features.h, src/shogun/kernel/DotKernel.h, src/shogun/kernel/Kernel.cpp, tests/unit/features/DenseSubSamplesFeatures_unittest.cc
=> Compatible kernel computation

src/shogun/optimization/FirstOrderBoundConstraintsCostFunction.h, src/shogun/optimization/NLOPTMinimizer.cpp, src/shogun/optimization/NLOPTMinimizer.h, tests/unit/optimization/NLOPTMinimizer_unittest.cc, tests/unit/optimization/NLOPTMinimizer_unittest.h, tests/unit/optimization/lbfgs/LBFGSMinimizer_unittest.cc
@karlnapf 
This is a wrapped NLOpt minimizer based on the minimizer framework for GP
ref:
https://github.com/shogun-toolbox/shogun/issues/2853
=> Nlopt minimizer

src/shogun/optimization/SGDMinimizer.cpp, src/shogun/optimization/SGDMinimizer.h, tests/unit/optimization/SGDMinimizer_unittest.cc, tests/unit/optimization/SGDMinimizer_unittest.h
@lisitsyn 
@iglesias 
@karlnapf 
You may take a look.
=> Sgd minimizer

src/shogun/lib/Map.h, src/shogun/lib/StringMap.h, tests/unit/lib/StringMap_unittest.cc
https://github.com/shogun-toolbox/shogun/issues/2904
=> String map

src/shogun/optimization/AdaDeltaUpdater.cpp, src/shogun/optimization/AdaDeltaUpdater.h, src/shogun/optimization/AdaptMomentumCorrection.h, src/shogun/optimization/ConstLearningRate.h, src/shogun/optimization/DescendCorrection.h, src/shogun/optimization/DescendUpdaterWithCorrection.h, src/shogun/optimization/InverseScalingLearningRate.h, src/shogun/optimization/MinimizerContext.h, src/shogun/optimization/MomentumCorrection.h, src/shogun/optimization/NesterovMomentumCorrection.h, src/shogun/optimization/RmsPropUpdater.cpp, src/shogun/optimization/RmsPropUpdater.h, src/shogun/optimization/StandardMomentumCorrection.h, tests/unit/optimization/StochasticMinimizers_unittest.cc, tests/unit/optimization/StochasticMinimizers_unittest.h
The idea of Adaptive momentum is
* to increase the `next` gradient if the sign of velocity and the sign of `current` gradient are agreed
* to discount the `next` gradient if the sign of velocity and the sign of `current` gradient are not agreed
=> added more updaters and learning rate for the minimizer framework

src/shogun/machine/gp/GaussianARDSparseKernel.cpp, src/shogun/machine/gp/GaussianARDSparseKernel.h
Reverts shogun-toolbox/shogun#2906
=> Revert "rename init() method in GP"

src/shogun/base/maybe.h, tests/unit/base/Maybe_unittest.cc
Work in progress but please comment
=> Added maybe - a holder for potentially absent values

src/shogun/optimization/L1Penalty.h
=> fix a typo

src/shogun/lib/StringMap.h, src/shogun/optimization/MinimizerContext.h, src/shogun/optimization/NLOPTMinimizer.h
@karlnapf 
Let's see if this patch can fix 3 warnings or not.
=> fixed warnings

src/interfaces/r_modular/CMakeLists.txt
=> set working-dir properly when running R

src/shogun/optimization/AdaptMomentumCorrection.h, src/shogun/optimization/NesterovMomentumCorrection.h
@karlnapf 
this PR should fix all  python_modular warnings related to the optimization framework.
=> updated docs to fix  python_modular warnings

src/shogun/features/StringFileFeatures.cpp, src/shogun/optimization/lbfgs/lbfgs.cpp
=> fix warnings issued by gcc 6

src/shogun/distributions/HMM.cpp
=> fix Wstrict-overflow

configs/Dockerfile
to allow cookbook building in travis
=> add cookbook dependencies

doc/cookbook/source/conf.py, examples/meta/generator/generate.py, examples/meta/generator/targets/ruby.json, examples/meta/generator/translate.py, examples/meta/ruby/CMakeLists.txt
=> added ruby to meta examples, cookbook, and test build

src/.doxy2swig.py
Doxy2Swig should write UTF-8 encoded strings to the output-file.
=> write output with utf-8 encoding

src/shogun/multiclass/KNN.h
Fixed the bugs in #2996 . Didn't change much though.
=> Fixed latex

src/shogun/distance/EuclideanDistance.cpp, tests/unit/distance/EuclideanDistance_unittest.cc
some fixes after https://github.com/shogun-toolbox/shogun/pull/3042.
=> minor fixes HAVE_LINALG

examples/meta/cpp/CMakeLists.txt, examples/meta/csharp/CMakeLists.txt, examples/meta/java/CMakeLists.txt, examples/meta/lua/CMakeLists.txt, examples/meta/octave/CMakeLists.txt, examples/meta/python/CMakeLists.txt, examples/meta/r/CMakeLists.txt, examples/meta/ruby/CMakeLists.txt, tests/meta/CMakeLists.txt
to fix centos buildbot with its ancient cmake version
=> fix cmake build for version <= 2.8.11

src/shogun/mathematics/linalg/internal/implementation/Dot.h, src/shogun/mathematics/linalg/internal/implementation/Max.h, tests/unit/mathematics/linalg/DotProduct_unittest.cc, tests/unit/mathematics/linalg/Max_unittest.cc
=> remove native dot and max in linalg

src/shogun/mathematics/linalg/internal/implementation/Scale.h, src/shogun/mathematics/linalg/internal/implementation/VectorSum.h, tests/unit/mathematics/linalg/Scale_unittest.cc, tests/unit/mathematics/linalg/VectorSum_unittest.cc
=> remove native scale and vector sum in linalg

doc/cookbook/source/examples/regression/linear_ridge_regression.rst, examples/meta/src/regression/linear_ridge_regression.sg
Shows api to extract weights in the lrr cookbook page
=> add get_w to lrr cookbook page

src/shogun/multiclass/LaRank.cpp, src/shogun/multiclass/LaRank.h, tests/unit/multiclass/LaRank_unittest.cc
Fix issue: https://github.com/shogun-toolbox/shogun/issues/3075
Sorry I messed up my previous PR with an improper rebase…
=> Bugfix: 3075

tests/unit/classifier/LDA_unittest.cc
Fixes https://github.com/shogun-toolbox/shogun/issues/3107
=> Fix broken LDA unit test

src/shogun/mathematics/linalg/internal/implementation/RangeFill.h, src/shogun/mathematics/linalg/internal/modules/Core.h, tests/unit/mathematics/linalg/RangeFill_unittest.cc
Continuing #2745 
added RangeFill.h,rangeFill in Core.h and RangeFill_unittest.
=> added rangeFill for linalg

examples/undocumented/libshogun/classifier_mkl_svmlight_modelselection_bug.cpp, examples/undocumented/libshogun/evaluation_cross_validation_classification.cpp, examples/undocumented/libshogun/evaluation_cross_validation_knn.cpp, examples/undocumented/libshogun/evaluation_cross_validation_locked_comparison.cpp, examples/undocumented/libshogun/evaluation_cross_validation_multiclass.cpp, examples/undocumented/libshogun/evaluation_cross_validation_multiclass_mkl.cpp, examples/undocumented/libshogun/evaluation_cross_validation_regression.cpp, examples/undocumented/libshogun/mathematics_confidence_intervals.cpp, examples/undocumented/libshogun/modelselection_combined_kernel_sub_parameters.cpp, examples/undocumented/libshogun/modelselection_grid_search_kernel.cpp, examples/undocumented/libshogun/modelselection_grid_search_krr.cpp, examples/undocumented/libshogun/modelselection_grid_search_multiclass_svm.cpp, examples/undocumented/libshogun/modelselection_grid_search_string_kernel.cpp, src/shogun/lib/external/cdflib.cpp, src/shogun/lib/external/cdflib.hpp, src/shogun/mathematics/Statistics.cpp, src/shogun/mathematics/Statistics.h, tests/unit/mathematics/Statistics_unittest.cc
- added incomplete_beta from libcdf (wrapper in CStatistics)
- also, added unit-tests, asserted against values computed from octave
@karlnapf please have a look!
=> removed compilation errors, added libcdf

src/shogun/clustering/KMeansLloydImpl.cpp
A way to parallelize computations in KMeans using OpenMP .
We can discuss here.
=> parallelize Kmeans computations

src/shogun/mathematics/linalg/internal/implementation/Cholesky.h, src/shogun/mathematics/linalg/internal/modules/Redux.h, tests/unit/mathematics/linalg/Cholesky_unittest.cc
added cholesky decomposition with eigen3 backend in linalg.
=> added cholesky decomposition in linalg

configs/Dockerfile
Installs matplotlib in travis docker builds. For #3146
=> update docker config to install matplotlib

src/shogun/classifier/GaussianProcessClassification.cpp, src/shogun/classifier/GaussianProcessClassification.h, src/shogun/machine/GaussianProcessMachine.cpp, src/shogun/machine/GaussianProcessMachine.h, src/shogun/machine/gp/FITCInferenceMethod.cpp, src/shogun/machine/gp/FITCInferenceMethod.h, src/shogun/machine/gp/SingleFITCLaplacianBase.cpp, src/shogun/machine/gp/SingleFITCLaplacianBase.h, src/shogun/machine/gp/SingleFITCLaplacianInferenceMethod.cpp, src/shogun/machine/gp/SingleFITCLaplacianInferenceMethod.h, src/shogun/machine/gp/SingleFITCLaplacianInferenceMethodWithLBFGS.cpp, src/shogun/machine/gp/SingleFITCLaplacianInferenceMethodWithLBFGS.h, src/shogun/machine/gp/SingleSparseInferenceBase.cpp, src/shogun/machine/gp/SingleSparseInferenceBase.h, src/shogun/machine/gp/SparseVGInferenceMethod.cpp, src/shogun/machine/gp/SparseVGInferenceMethod.h, src/shogun/regression/GaussianProcessRegression.cpp, src/shogun/regression/GaussianProcessRegression.h, tests/unit/classifier/GaussianProcessClassification_unittest.cc, tests/unit/machine/gp/FITCInferenceMethod_unittest.cc, tests/unit/machine/gp/SingleFITCInferenceBase_unittest.cc, tests/unit/machine/gp/SingleFITCLaplacianInferenceMethodWithLBFGS_unittest.cc, tests/unit/machine/gp/SingleFITCLaplacianInferenceMethod_unittest.cc, tests/unit/machine/gp/SparseVGInferenceMethod_unittest.cc, tests/unit/optimization/NLOPTMinimizer_unittest.cc, tests/unit/optimization/NLOPTMinimizer_unittest.h, tests/unit/regression/GaussianProcessRegression_unittest.cc
=> FITC methods are included in the BSD-only Shogun

src/shogun/kernel/GaussianARDKernel.cpp, src/shogun/machine/gp/SingleSparseInferenceBase.cpp, src/shogun/machine/gp/SingleSparseInferenceBase.h, src/shogun/optimization/NLOPTMinimizer.cpp, src/shogun/optimization/NLOPTMinimizer.h, tests/unit/optimization/NLOPTMinimizer_unittest.cc, tests/unit/optimization/NLOPTMinimizer_unittest.h
=> Using the NLOPT wrapper in the optimization framework (1)

src/shogun/mathematics/linalg/internal/implementation/Cholesky.h
added a missing definition of ReturnType in Cholesky.h
=> fix for PR #3144

src/shogun/machine/gp/EPInferenceMethod.cpp, src/shogun/machine/gp/EPInferenceMethod.h, src/shogun/machine/gp/ExactInferenceMethod.cpp, src/shogun/machine/gp/ExactInferenceMethod.h, src/shogun/machine/gp/FITCInferenceMethod.cpp, src/shogun/machine/gp/FITCInferenceMethod.h, src/shogun/machine/gp/InferenceMethod.cpp, src/shogun/machine/gp/InferenceMethod.h, src/shogun/machine/gp/SparseVGInferenceMethod.cpp, src/shogun/machine/gp/SparseVGInferenceMethod.h
=> refactor the GP framework 1

src/shogun/machine/gp/InferenceMethod.h, src/shogun/machine/gp/KLApproxDiagonalInferenceMethod.cpp, src/shogun/machine/gp/KLApproxDiagonalInferenceMethod.h, src/shogun/machine/gp/KLCholeskyInferenceMethod.cpp, src/shogun/machine/gp/KLCholeskyInferenceMethod.h, src/shogun/machine/gp/KLCovarianceInferenceMethod.cpp, src/shogun/machine/gp/KLCovarianceInferenceMethod.h, src/shogun/machine/gp/KLDualInferenceMethod.cpp, src/shogun/machine/gp/KLDualInferenceMethod.h, src/shogun/machine/gp/KLInferenceMethod.cpp, src/shogun/machine/gp/KLInferenceMethod.h
=> refactor the GP framework 2

src/shogun/machine/gp/KLDualInferenceMethod.cpp, src/shogun/machine/gp/KLDualInferenceMethod.h, src/shogun/optimization/lbfgs/LBFGSMinimizer.cpp
@karlnapf 
This PR will break the GPC notebook.
I will fix the notebook issue next week.
=> refactor the GP framework 3

examples/meta/generator/parse.py, examples/meta/generator/targets/cpp.json, examples/meta/generator/targets/csharp.json, examples/meta/generator/targets/java.json, examples/meta/generator/targets/lua.json, examples/meta/generator/targets/octave.json, examples/meta/generator/targets/python.json, examples/meta/generator/targets/r.json, examples/meta/generator/targets/ruby.json, examples/meta/generator/translate.py
Cherry picked from https://github.com/shogun-toolbox/shogun/tree/feature/bigtest
=> allow for static method calls in meta examples

configs/Dockerfile
Fixed missing software-properties-common package error.
Fixes #3200 Docker missing package error.
=> Fixed missing software-properties-common package error.

examples/meta/generator/targets/python.json, examples/meta/generator/translate.py
Fixes issue with imports of classes which are used for static methods calls #3183
=> Meta Language fix static call import

NEWS, src/shogun/evaluation/CrossValidation.cpp, src/shogun/evaluation/CrossValidation.h, tests/unit/evaluation/CrossValidation_multithread_unittest.cc
=> parallel xval with clone

examples/meta/generator/targets/cpp.json
This adds the RealDistance type and makes it available within cookbooks.
=> Make RealDistance type available within cookbooks.

doc/cookbook/source/index.rst
This adds Distance listing for Cookbook generation.
=> Adds Distance listing for Cookbook generation.

benchmarks/linalg_benchmark.cpp, benchmarks/linalg_refactor_benchmark.cpp
@lambday Compatible with the cleaned-up linalg (Class name, unique_ptr)
=> linalg benchmark update

doc/ipython-notebooks/neuralnets/autoencoders.ipynb, doc/ipython-notebooks/neuralnets/neuralnets_digits.ipynb, src/shogun/io/NeuralNetworkFileReader.cpp, src/shogun/neuralnets/Autoencoder.cpp, src/shogun/neuralnets/Autoencoder.h, src/shogun/neuralnets/DeepAutoencoder.cpp, src/shogun/neuralnets/NeuralNetwork.cpp, src/shogun/neuralnets/NeuralNetwork.h, tests/unit/io/NeuralNetworkFileReader_unittest.cc, tests/unit/neuralnets/NeuralNetwork_unittest.cc
Not merge ready. I'm getting [this error](http://pastebin.com/mDkMqaa6) with `PythonModular=ON`. It's an easy compiler error but I'm not able to debug it.
=> add setters/getters in nn and autoencoders

examples/meta/src/clustering/gmm.sg
For adding integration data for GMM cookbook page
=> init math for gmm cookbook integration data

examples/meta/generator/targets/cpp.json
This adds the  DenseDistance type and makes it available within cookbooks.
=> Make RealDenseDistance type available within cookbooks.

examples/meta/generator/generate.py
Fixes exception to be Python 2 and 3 compatible.
=> Fix Python 2 to 3 exception conversion.

setup.py
Shogun Python package using setup.py
=> Shogun Python package using setup.py

doc/cookbook/source/examples/classifier/kernel_svm.rst
=> minor correction in svm cookbook

src/shogun/kernel/ShiftInvariantKernel.cpp, src/shogun/kernel/ShiftInvariantKernel.h, tests/unit/kernel/ShiftInvariantKernel_unittest.cc
@karlnapf hey! Please have a look. Will send the gaussian kernel refactoring in another patch.
=> added translational invariant kernel class, refactored distance kernel

src/shogun/distance/Distance.cpp, src/shogun/distance/Distance.h, src/shogun/distance/EuclideanDistance.cpp, src/shogun/distance/EuclideanDistance.h, src/shogun/statistics/MMDKernelSelectionMedian.cpp, tests/unit/distance/EuclideanDistance_unittest.cc
=> Refactored EuclideanDistance to work with any CDotFeatures

src/interfaces/modular/Kernel.i, src/interfaces/modular/Kernel_includes.i, src/shogun/kernel/GaussianCompactKernel.cpp, src/shogun/kernel/GaussianKernel.cpp, src/shogun/kernel/GaussianKernel.h, src/shogun/kernel/ShiftInvariantKernel.cpp, src/shogun/kernel/ShiftInvariantKernel.h, tests/unit/base/SGObject_unittest.cc
@karlnapf please have a  look!
=> refactored GaussianKernel as a subclass of CShiftInvariantKernel

src/interfaces/modular/NeuralNets.i, src/shogun/neuralnets/NeuralLayers.h
For #3246. Fixes segfault while doing:
```
layers = NeuralLayers()
layers = layers.input(num_feats)
layers = layers.linear(50)
layers = layers.softmax(2)
```
=> add %newobject in neuralnet interface

src/shogun/multiclass/ShareBoost.cpp
=> update shareboost error msg / update shareboost nonzero feat num boundary

src/shogun/regression/KRRNystrom.cpp, src/shogun/regression/KRRNystrom.h, src/shogun/regression/KernelRidgeRegression.h, tests/unit/regression/krrnystrom_unittest.cc
Hey here is my PR.
#TODO's in the code should be attended to or removed.
Added a normal example in the meantime.
=> Implement the Nystrom approximate algorithm for KRR

doc/cookbook/source/examples/multiclass_classifier/shareboost.rst, doc/cookbook/source/references.bib
=> shareboost cookbook minor fix

src/shogun/base/SGObject.cpp, src/shogun/base/SGObject.h, src/shogun/lib/any.h, src/shogun/lib/basetag.h, src/shogun/lib/tag.h, src/shogun/modelselection/ParameterCombination.cpp, src/shogun/multiclass/ecoc/ECOCDiscriminantEncoder.cpp, src/shogun/structure/GEMPLP.cpp, src/shogun/transfer/multitask/MultitaskKernelTreeNormalizer.h, src/shogun/transfer/multitask/MultitaskLinearMachine.cpp, src/shogun/transfer/multitask/MultitaskROCEvaluation.cpp, tests/unit/base/MockObject.h, tests/unit/base/SGObject_unittest.cc, tests/unit/lib/Any_unittest.cc
=> Implement tag-based parameters in SGObject

examples/meta/generator/generate.py, examples/meta/generator/translate.py
=> Improve meta language error messages

src/shogun/optimization/AdamUpdater.cpp, src/shogun/optimization/AdamUpdater.h, tests/unit/optimization/StochasticMinimizers_unittest.cc
@karlnapf 
I will add the doc soon.
=> added the Adam method

src/shogun/mathematics/linalg/LinalgBackendViennacl.h
@karlnapf  @lambday 
Is it possible to merge this PR soon so I can rebase other PRs on it? Thanks!
=> LinalgRefactor_add BackendViennaCL typecast helper method

examples/meta/src/neural_nets/feedforward_net_classification.sg
=> minor change in neural net classification cookbook

src/shogun/mathematics/linalg/GPUMemoryBase.h, src/shogun/mathematics/linalg/LinalgNamespace.h
=> LinalgRefactor-doxygen fix patch

src/shogun/lib/SGMatrix.cpp, src/shogun/lib/SGMatrix.h, src/shogun/mathematics/linalg/LinalgBackendBase.h, src/shogun/mathematics/linalg/LinalgBackendGPUBase.h, src/shogun/mathematics/linalg/LinalgBackendViennacl.h, src/shogun/mathematics/linalg/LinalgNamespace.h, tests/unit/mathematics/linalg/LinalgBackendBase_unittest.cc, tests/unit/mathematics/linalg/LinalgBackendViennaCL_unittest.cc
- Added SGMatrix and GPUMemoryViennaCL interface
- SGMatrix sum() with Eigen3 and ViennaCL
--- UPDATE Jul 13th ---
Refactored PR.
SGMatrix with GPU memory transfer unit-tests. 
Updated based on #3363 and #3346
=> LinalgRefactor - matrix

src/shogun/mathematics/linalg/GPUMemoryViennaCL.h, src/shogun/mathematics/linalg/LinalgBackendViennacl.h
To distinguish from data_matrix method #3382
=> LinalgRefactor - rename gpumemory data method

src/shogun/lib/any.h
Can't believe I got this merged in develop.
=> fix bug in any

cmake/FindMetaExamples.cmake
fix the bug at https://github.com/shogun-toolbox/shogun/issues/3386
=> fix a bug in cmake

src/shogun/base/SGObject.h, src/shogun/lib/any.h
=> update indentations and whitespace in SGObject and Any

src/shogun/labels/DenseLabels.h, src/shogun/regression/LeastAngleRegression.cpp, src/shogun/regression/LeastAngleRegression.h, tests/unit/regression/lars_unittest.cc
=> LARS float support cleanup patch (for PR #3133)

src/shogun/mathematics/linalg/LinalgBackendBase.h, src/shogun/mathematics/linalg/LinalgBackendEigen.h, src/shogun/mathematics/linalg/LinalgNamespace.h, src/shogun/mathematics/linalg/internal/Block.h, tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
=> LinalgRefactor - matrix block sum

src/shogun/base/SGObject.cpp, src/shogun/base/SGObject.h, src/shogun/lib/SGReferencedData.cpp, src/shogun/lib/SGReferencedData.h, src/shogun/lib/SGVector.cpp, src/shogun/lib/SGVector.h, src/shogun/lib/any.h, src/shogun/lib/common.h, tests/unit/io/CerealObject.h, tests/unit/io/Cereal_unittest.cc
class Any serialization.
- Changes in any.h and any.cpp
- Need rebase on #3226
=> Cereal serialization - SGObejct

examples/meta/generator/targets/java.json
Sorry, I accidentally undid the changes in #3408 in my last PR.
=> Fix java enum imports and literals again

src/shogun/base/MetaClass.h, src/shogun/base/library.cpp, src/shogun/base/library.h, src/shogun/base/manifest.cpp, src/shogun/base/manifest.h, src/shogun/lib/any.h, tests/unit/CMakeLists.txt, tests/unit/base/MockBaseClass.h, tests/unit/base/MockLibrary.cpp, tests/unit/base/MockLibraryWOManifest.cpp, tests/unit/base/Plugin_unittest.cc, tests/unit/lib/Any_unittest.cc
@lisitsyn @karlnapf 
Work in progress. :construction: :construction_worker:
Need to add documentation and checks for corner cases.
Please review and tell what needs to be changed.
@lisitsyn how to add create() in this and the plugins that it will be loading :question:
=> add plugins functionality

src/shogun/mathematics/linalg/LinalgBackendBase.h, src/shogun/mathematics/linalg/LinalgBackendEigen.h, src/shogun/mathematics/linalg/LinalgNamespace.h, tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
=> LinalgRefactor-SGVector-Rangefill

src/shogun/multiclass/QDA.cpp
=> FIX #3218: Remove #ifdef for debugging.

src/shogun/kernel/CombinedKernel.cpp
=> fix a bug in CombinedKernel

src/shogun/kernel/CombinedKernel.cpp, src/shogun/kernel/CombinedKernel.h
=> enable MKL in GP

src/interfaces/modular/Minimizer.i, src/shogun/machine/gp/SingleSparseInference.cpp, src/shogun/optimization/NLOPTMinimizer.cpp, src/shogun/optimization/NLOPTMinimizer.h, src/shogun/optimization/lbfgs/LBFGSMinimizer.h, src/shogun/optimization/nloptcommon.h, tests/unit/modelselection/GradientModelSelection_unittest.cc
@karlnapf 
Users can use NLOPT in python
```
minimizer2 = sg.NLOPTMinimizer()
minimizer2.set_nlopt_parameters(sg.LD_MMA) #using MMA 
grad_search.set_minimizer(minimizer2)
```
=> fixed issues related to nlopt

.gitmodules, NEWS, src/shogun/lib/external/cdflib.cpp
@vigsterkr please merge once buildbot is free
=> Feature/post release 5.0 fixes

doc/ipython-notebooks/intro/Introduction.ipynb
=> Fix a few links in the notebook

doc/ipython-notebooks/classification/HashedDocDotFeatures.ipynb
Converted from an older notebook format (v3) to the format (v4)
=> Converted from an older notebook format (v3) to the format (v4)

tests/meta/CMakeLists.txt
echo solution for CMake error, for there is no meta examples.#3535
=> echo solution for CMake error  #3535

src/shogun/multiclass/QDA.cpp
Replacing the old pointer and vlen with `SGVector`.
#3218.
@karlnapf : The tests have passed. Review.
=> Replace pointer and vlen with SGVector in QDA.

examples/meta/generator/translate.py
For fixing the weird corner-case of octave boolean arrays
* Octave indexing starts with 1
* For bool vectors, octave doesnt have a working typemap, cf #3552
* When using native `SGVector` / `SGMatrix` calls, the indices need to start with 0
* If this is not done, then allocating a new boolean vector in meta example, such as in #3282 , results in uninitialised memory errors as the 0-element is never written.
Hurray!
=> Do not offset vector/matrix indices when shogun's native access methods are used

doc/cookbook/source/templates/layout.html
'new async' tracking code added to the end of \<head> tag
=> adding GA tracker to cookbooks

doc/ipython-notebooks/classification/HashedDocDotFeatures.ipynb
Formatted the Notebook according to the new template and moved the `special thanks` section in the end.
=> Formatted the Notebook according to the new template

src/shogun/multiclass/tree/ID3ClassifierTree.h
non-categorical attributes , categorical attributes may be some confused. I changed to features and Labels.
=> change doc to disambiguate.

doc/cookbook/source/examples/regression/krr_nystrom.rst, doc/cookbook/source/references.bib, examples/meta/src/regression/krr_nystrom.sg
=> Nystrom cookbook

src/shogun/mathematics/linalg/LinalgNamespace.h
=> LinalgRefacto - Move gpu transfer methods to the front

src/shogun/lib/SGMatrix.cpp, src/shogun/lib/SGVector.cpp, src/shogun/mathematics/linalg/GPUMemoryBase.h, src/shogun/mathematics/linalg/GPUMemoryViennaCL.h, tests/unit/mathematics/linalg/LinalgBackendViennaCL_unittest.cc
It actually wasn't working before..
=> LinalgRefacotr - Fix GPU Vector/Matrix deep cloning

examples/meta/CMakeLists.txt
=> Make meta_examples depend on python generator and language files.

src/shogun/modelselection/ModelSelectionParameters.cpp, src/shogun/modelselection/ModelSelectionParameters.h
Function template was not accessible
=> Fix CModelSelectionParameters::set_values()

src/shogun/mathematics/linalg/GPUMemoryBase.h, src/shogun/mathematics/linalg/GPUMemoryViennaCL.h, src/shogun/mathematics/linalg/LinalgBackendBase.h, src/shogun/mathematics/linalg/LinalgBackendEigen.h, src/shogun/mathematics/linalg/LinalgBackendGPUBase.h, src/shogun/mathematics/linalg/LinalgBackendViennacl.h, src/shogun/mathematics/linalg/LinalgNamespace.h, src/shogun/mathematics/linalg/SGLinalg.h, src/shogun/mathematics/linalg/internal/modules/SpecialPurpose.h, src/shogun/mathematics/linalg/linalg.h
=> LinalgRefactor - clean up documentations and styles

src/shogun/evaluation/CrossValidation.cpp
* CList::get_first_element() is potentially not thread-safe
* CEvaluation object was shared
This does not solve all of the problem. The problem persists at a lower frequency. I'll open an issue on this.
=> Fix data races in CCrossValidation::evaluate_one_run()

src/shogun/clustering/KMeansMiniBatch.cpp
=> Fix KMeansMiniBatch memcheck error

src/shogun/lib/memory.h, tests/unit/lib/Memory_unittest.cc
=> added shogun::memcpy wrapper for std::memcpy

src/shogun/lib/SGMatrix.cpp, src/shogun/lib/SGMatrix.h, src/shogun/multiclass/MCLDA.cpp, src/shogun/neuralnets/NeuralNetwork.cpp, tests/unit/lib/SGMatrix_unittest.cc
=> SGMatrix cleanups and speedups

doc/cookbook/source/examples/distance/braycurtis.rst, doc/cookbook/source/examples/distance/mahalanobis.rst
Fix for #3593. 
@karlnapf It fixes the warning you suggested. Sorry for the late edit, it just slipped out of my mind.
=> Minor fix for cookbook

src/interfaces/csharp_modular/swig_typemaps.i, src/interfaces/java_modular/swig_typemaps.i, src/interfaces/lua_modular/swig_typemaps.i, src/interfaces/modular/abstract_types_extension.i, src/interfaces/perl_modular/swig_typemaps.i, src/interfaces/python_modular/swig_typemaps.i, src/interfaces/r_modular/swig_typemaps.i, src/interfaces/ruby_modular/swig_typemaps.i
=> clean up memcpy in swig typemaps

tests/unit/CMakeLists.txt
=> Move generated serialization unit tests into separate executable

src/shogun/classifier/svm/SVM.cpp, src/shogun/classifier/svm/SVM.h
=> use get and set in SVM class

src/shogun/evaluation/CrossValidation.cpp
This needs to be done more carefully, see #3743
=> xvalidation back to one thread

doc/ipython-notebooks/clustering/GMM.ipynb, doc/ipython-notebooks/evaluation/xval_modelselection.ipynb, doc/ipython-notebooks/statistical_testing/mmd_two_sample_testing.ipynb
=> Fixed broken links in ipython notebooks

src/shogun/classifier/AveragedPerceptron.h
changed "lerning" to "learning" on line 26;
changed "learn data" to learning data on 75;
=> Fixed typos

doc/ipython-notebooks/gaussian_process/variational_classifier.ipynb
#3757 
@vigsterkr It's throwing a few warnings. But all the errors have been dealt with now. Sorry for the initial mistake
=> Fixed Error in variational_classifier

src/interfaces/octave_modular/swig_typemaps.i
=> temporarily set number of threads in octave to one, known issue #3772

doc/cookbook/source/examples/statistical_testing/linear_time_mmd.rst, doc/cookbook/source/examples/statistical_testing/quadratic_time_mmd.rst
Testing the resurrected cookbook PR preview
=> remove CKernelSelectionStrategy reference and minor clean-ups

configs/shogun-sdk/Dockerfile
=> Add clang-format-3.8 to Docker image.

src/shogun/base/some.h
@lisitsyn 
Only https://github.com/geektoni/shogun/commit/1bcd13f9c91499dbb35e69ec294eb630e61590d5 is relevant since the other one is just to fix style errors.
=> Refactor Some<> to make it a bit more standalone. 

.gitignore, src/shogun/base/some.h, tests/unit/base/Some_unittest.cc
@lisitsyn 
Changes:
* Fix the SGObject equals() (in view of SG_REF refactor);
* get() method permits to extract the raw pointer from Some<> (in view of SG_REF refactor);
Other changes:
* Add .idea (CLion IDE directory) to .gitignore;
=> Add new constructor and get() method to Some<>.

src/shogun/base/progress.h, tests/unit/base/PRange_unittest.cc
@vigsterkr This patch works for single-threaded environments. <del>It needs further development when used with OpenMP</del>.
=> [ProgressBar] Add a boolean flag to the progress bar.

src/shogun/base/progress.h, src/shogun/base/range.h, tests/unit/base/PRange_unittest.cc
<del>This needs #3829 to be merged first.</del>
=> [ProgressBar] Refactor the progress bar code and add documentation.

configs/shogun-sdk/Dockerfile
=> [PrematureStopping] Add RxCpp to the Docker image.

src/shogun/features/DataGenerator.cpp, src/shogun/features/DataGenerator.h, src/shogun/mathematics/linalg/LinalgNamespace.h, tests/unit/base/main_unittest.cc, tests/unit/classifier/svm/SVMOcas_unittest.cc, tests/unit/environments/GaussianCheckerboard.h, tests/unit/environments/LinearTestEnvironment.h, tests/unit/environments/MutiLabelTestEnvironment.h, tests/unit/multiclass/MulticlassOCAS_unittest.cc
This pr is about to add a global fixture to share mock data between different tests. Haven't done yet because I believe there are a lot detail need to discuss. Honestly speaking, I'm really not good at naming things like file and class or variable:/  I will add comments later!
=> Add global fixture with label data

tests/unit/environments/GaussianCheckerboard.h
=> Fix memleak in GaussianCheckerboard

src/shogun/mathematics/linalg/GPUMemoryBase.h, src/shogun/mathematics/linalg/GPUMemoryViennaCL.h, src/shogun/mathematics/linalg/LinalgBackendBase.h, src/shogun/mathematics/linalg/LinalgBackendEigen.cpp, src/shogun/mathematics/linalg/LinalgBackendEigen.h, src/shogun/mathematics/linalg/LinalgBackendGPUBase.h, src/shogun/mathematics/linalg/LinalgBackendViennaCL.h, src/shogun/mathematics/linalg/LinalgBackendViennaclKernels.h, src/shogun/mathematics/linalg/LinalgMacros.h, src/shogun/mathematics/linalg/LinalgNamespace.h, src/shogun/mathematics/linalg/LinalgSpecialPurposes.h, src/shogun/mathematics/linalg/SGLinalg.h, src/shogun/mathematics/linalg/linalg.h
`clang-format-3.8 -i *.*` in path `src/shogun/mathematics/linalg/` with `./.clang-format` in docker.
No other changes.
=> Linalg Lib clang-format check

src/shogun/lib/SGMatrix.cpp, src/shogun/lib/SGMatrix.h, src/shogun/lib/SGVector.cpp, src/shogun/lib/SGVector.h, src/shogun/mathematics/linalg/LinalgBackendBase.h, src/shogun/mathematics/linalg/LinalgBackendEigen.h, src/shogun/mathematics/linalg/LinalgNamespace.h, src/shogun/mathematics/linalg/backend/eigen/BasicOps.cpp, src/shogun/mathematics/linalg/backend/eigen/Decompositions.cpp, src/shogun/preprocessor/KernelPCA.cpp, src/shogun/preprocessor/KernelPCA.h, tests/unit/lib/SGMatrix_unittest.cc, tests/unit/lib/SGVector_unittest.cc, tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc, tests/unit/preprocessor/KernelPCA_unittest.cc
Unit test back on, results are consistent with scikit's kpca but it may need some more testing.
=>  Port KernelPCA to use linalg and refactor unit test

src/shogun/converter/ica/FastICA.cpp, tests/unit/converter/ica/FastICA_unittest.cc
@karlnapf maybe something like this? :)
=> add error message when features are empty

src/shogun/CMakeLists.txt, src/shogun/classifier/svm/NewtonSVM.cpp, tests/unit/CMakeLists.txt, tests/unit/base/clone_unittest.cc.py, tests/unit/base/main_unittest.cc, tests/unit/base/trained_model_serialization_unittest.cc.jinja2, tests/unit/base/trained_model_serialization_unittest.cc.py, tests/unit/environments/RegressionTestEnvironment.h
=> Trained models serialization test

src/shogun/base/SGObject.cpp, src/shogun/base/SGObject.h
This enables the user to get a list of parameters which he can observe using a ParameterObserver object.
=> [ShogunBoard] Add methods to print a list of parameters which can be observed.

src/shogun/lib/any.h
=> Fix OSX and FreeBSD build.

src/shogun/labels/BinaryLabels.cpp, src/shogun/labels/BinaryLabels.h, src/shogun/labels/MulticlassLabels.cpp, src/shogun/labels/MulticlassLabels.h, tests/unit/labels/BinaryLabels_unittest.cc, tests/unit/labels/MulticlassLabels_unittest.cc
- BinaryLabels constructor with confidence scores is more intuitive (comparing >= threshold)
- Added MulticlassLabels constructor with probability matrix
=> Initialising BinaryLabels & MulticlassLabels with probabilities scores

examples/undocumented/libshogun/evaluation_cross_validation_mkl_weight_storage.cpp, examples/undocumented/python/evaluation_cross_validation_multiclass_storage.py, src/shogun/evaluation/CrossValidation.cpp, src/shogun/labels/MulticlassLabels.cpp, src/shogun/labels/MulticlassLabels.h, tests/unit/lib/parameter_observers/ParameterObserverCV_unittest.cc
@karlnapf this should address your last comments on the last PR :)
=> [ParameterObservers] Polish once more the new observable CrossValidation. 

tests/unit/classifier/GaussianProcessClassification_unittest.cc
This PR refactors GaussianProcessClassification_unittest.cc to use fixtures. (See issue #3947 ).
=> Refactor GaussianProcessClassification_unittest.cc to use fixtures

examples/meta/CMakeLists.txt, examples/meta/generator/parse.py
Solves #3999.
@vigsterkr Is the CMake change OK? I'm not sure if it's clean or hacky (not very experienced with CMake)
=> Fix meta example parser bug in parallel builds

src/shogun/clustering/GMM.cpp
Fix possible memory leaks in the GMM code, took me some time to get the idea of the ``train_smem`` method, but really liked the structure.
=> GMM: possible memory leaks.

src/interfaces/swig/SGBase.i, src/shogun/base/SGObject.h, src/shogun/lib/basetag.h
What works now:
```
>>> import shogun
>>> k = shogun.GaussianKernel()
>>> k.get_width()
1.0
>>> k.put('log_width', 3.5)
>>> k.get_width()
2193.266316856917
>>> k.get_float('log_width')
3.5
```
=> Support get/put in SWIG for some of types

src/interfaces/swig/SGBase.i, src/shogun/base/SGObject.cpp, src/shogun/base/SGObject.h, src/shogun/lib/any.h
Like that
```
>>> import shogun
>>> shogun.kernel('GaussianKernel')
GaussianKernel(cache_size=10,combined_kernel_weight=1,lhs=null,lhs_equals_rhs=false,log_width=-0.346574,m_distance=EuclideanDistance(...),m_precomputed_distance=null,normalizer=IdentityKernelNormalizer(...),num_lhs=0,num_rhs=0,opt_type=0,optimization_initialized=false,properties=,rhs=null)```
=> Implement parameter-based to_string

src/shogun/lib/SGVector.cpp, src/shogun/lib/SGVector.h, src/shogun/lib/any.cpp, src/shogun/lib/any.h, tests/unit/lib/Any_unittest.cc
@karlnapf I removed some SG_SDEBUG from any.h as it is kind of circular dependency. Gets too hard to test separately.
=> Implement clone for any

cmake/FindMetaExamples.cmake, src/shogun/clustering/GMM.cpp, src/shogun/clustering/GMM.h
This PR add unit test of GMM, and replace LAPACK usage with linalg . (#2747)
=> Use linalg in GMM

src/shogun/lib/SGSparseMatrix.cpp, src/shogun/lib/SGSparseMatrix.h, tests/unit/lib/SGSparseMatrix_unittest.cc
=> Add SGSparseMatrix equals and operator==

src/shogun/distributions/LinearHMM.cpp, src/shogun/kernel/string/WeightedDegreePositionStringKernel.cpp, src/shogun/kernel/string/WeightedDegreeStringKernel.cpp, src/shogun/multiclass/GMNPSVM.cpp, src/shogun/preprocessor/RandomFourierGaussPreproc.cpp
Made changes as suggested in #4110
=> Tag-register all raw matrices

src/shogun/base/AnyParameter.h
Enhancement suggested in #4123 review.
=> Add default arguments to AnyParameterProperties ctor

src/shogun/multiclass/KNN.cpp
=> Clean up error message in KNN

cmake/FindMetaExamples.cmake, src/shogun/regression/LinearRidgeRegression.cpp, src/shogun/regression/LinearRidgeRegression.h
This PR replaces lapack guard and Eigen usage with linalg in `LinearRidgeRegression`
=> Use linalg in LinearRidgeRegression

src/shogun/mathematics/linalg/LinalgBackendBase.h, src/shogun/mathematics/linalg/LinalgBackendEigen.h, src/shogun/mathematics/linalg/LinalgBackendViennaCL.h, src/shogun/mathematics/linalg/LinalgNamespace.h, src/shogun/mathematics/linalg/LinalgSpecialPurposes.h, src/shogun/mathematics/linalg/backend/eigen/SpecialPurposes.cpp
Continue work in #4159 and fix missing const qualifiers in ViennaCL backend
=> Add const qualifiers to input of linalg APIs and fix #4159

src/shogun/mathematics/linalg/LinalgBackendViennaCL.h
=> Add missing const qualifier in Vienna backend

src/shogun/metric/LMNN.cpp, src/shogun/metric/LMNNImpl.cpp, src/shogun/metric/LMNNImpl.h, tests/unit/metric/LMNNImpl_unittest.cc
=> Use linalg in place of Eigen in LMNN

src/shogun/labels/LabelsFactory.cpp, src/shogun/labels/LabelsFactory.h, src/shogun/latent/LatentModel.cpp, src/shogun/machine/MulticlassMachine.cpp, src/shogun/metric/LMNN.cpp, src/shogun/metric/LMNNImpl.cpp, src/shogun/multiclass/tree/CHAIDTree.cpp, tests/unit/base/Serialization_unittest.cc, tests/unit/clustering/kmeans_unittest.cc, tests/unit/multiclass/KNN_unittest.cc, tests/unit/multiclass/MCLDA_unittest.cc, tests/unit/multiclass/QDA_unittest.cc, tests/unit/regression/LibSVR_unittest.cc
[WIP] its a start towards eventually deleting CLabelsFactory.
=> revome methods from labels factory

src/interfaces/swig/SGBase.i, src/shogun/lib/StoppableSGObject.cpp, src/shogun/lib/StoppableSGObject.h, src/shogun/machine/Machine.cpp, src/shogun/machine/Machine.h
[WIP] This simply takes all premature stopping code and places it in a new class. Most of the python legacy examples broke locally. I am struggling with the swig part.
=> CStoppableSGObject class

src/shogun/classifier/AveragedPerceptron.cpp, src/shogun/classifier/LPBoost.cpp, src/shogun/classifier/Perceptron.cpp, src/shogun/classifier/mkl/MKL.cpp, src/shogun/classifier/mkl/MKLMulticlass.cpp, src/shogun/classifier/svm/LibLinear.cpp, src/shogun/classifier/svm/MPDSVM.cpp, src/shogun/classifier/svm/NewtonSVM.cpp, src/shogun/classifier/svm/OnlineSVMSGD.cpp, src/shogun/classifier/svm/SGDQN.cpp, src/shogun/classifier/svm/SVMLight.cpp, src/shogun/machine/KernelMachine.cpp, src/shogun/multiclass/KNN.cpp, src/shogun/transfer/multitask/LibLinearMTL.cpp
this mostly replaces cancel_computation calls with the COMPUTATION_CONTROLLERS macro
=> replacing cancel_computation() with macro

src/shogun/evaluation/CrossValidation.cpp, src/shogun/evaluation/MachineEvaluation.cpp, src/shogun/evaluation/MachineEvaluation.h, src/shogun/machine/Machine.h
removes duplicate code from CMachineEvaluation
=> inherit stoppable sgobject code in CMachineEvaluation

src/shogun/base/Parallel.cpp
Cleanup:
Removed ifdef HAVE_CXX11 and if HAVE_CXX11
Issue #4284
=> Cleanup: Removed HAVE_CXX11 Issue #4284

examples/meta/src/evaluation/cross_validation_support_vector_machine.sg, src/shogun/evaluation/StratifiedCrossValidationSplitting.cpp, src/shogun/lib/SGVector.cpp, src/shogun/lib/SGVector.h, tests/unit/lib/SGVector_unittest.cc
this unblocks @FaroukY and is way better style
That stratification code could need some love as well...
=> avoid specialisation of labels in stratified xvalidation

src/shogun/base/init.cpp, src/shogun/multiclass/LSHKNNSolver.h
Removed #ifndef HAVE_CXX11
Issue #4284
=> [Issue #4284] Removed HAVE_CX11

src/shogun/evaluation/CrossValidation.cpp
previously, this was only done for number of threads >1 which lead to inconsistent behaviour.
@FaroukY this will fix your problem with the failing integration test from octave (which currently is enforced to use a single thread only)
As long as our features are used in a non-read-only fashion, this unfortunately is the only way of guaranteeing correct results in xvalidation. As soon as we have
''CMachine::train(const CFeatures*, const CLabels*)`, this can be updated in a way that features are shared across folds. And then we can also re-enable multithreaded xvaldiation without getting a huge number of race conditions and memory errors.
@vinx13 we are counting on you ;)
=> make xvalidation always leave state of machine/features invariant

src/shogun/classifier/Perceptron.cpp, tests/unit/classifier/Perceptron_unittest.cc
We want to update the weights vector in each iteration so that we remain consistent during a paused state
=> state update in each iteration for perceptron

src/shogun/CMakeLists.txt, src/shogun/util/PutPerceptron_benchmark.cc
[WIP] we could iterate over this a bit to clean it up :)
=> benchmark put with perceptron

src/interfaces/swig/Classifier.i, src/interfaces/swig/Classifier_includes.i, src/shogun/classifier/svm/NewtonSVM.cpp, src/shogun/classifier/svm/NewtonSVM.h, src/shogun/machine/IterativeMachine.h
[WIP] as state is not updated properly yet so there is nothing meaningful available when we cancel. 
we can first merge #4346 first and then rebase here as a test.
=> iterative machine in NewtonSVM

examples/meta/src/binary/svmlin.sg, examples/meta/src/binary/svmsgd.sg
Two files are missing from previous pr #4361, data shogun-toolbox/shogun-data#168
See also #4400
=> Add svmlin & svmsgd meta example

src/interfaces/python/swig_typemaps.i
This PR addresses #4461. 
Still need to think a bit more about docstrings and maybe error handling.
@karlnapf Is this what you were thinking (more or less)?
=> simplified object instantiation in Python API

examples/meta/generator/parse.py, examples/meta/src/meta_api/literals.sg
=> Add support for negative numeric literals in the meta language

examples/meta/generator/targets/python.json, examples/meta/src/pipeline/pipeline.sg, src/interfaces/python/swig_typemaps.i, src/interfaces/swig/SGBase.i, src/interfaces/swig/shogun.i
=> added remaining factory functions to Python API

src/interfaces/swig/Machine.i
#4463 
@gf712 @avramidis @vinx13 @shubham808 we need more of those
=> remove LinearRidgeRegression from SWIG

examples/undocumented/python/evaluation_cross_validation_regression.py, examples/undocumented/python/modelselection_grid_search_krr.py, src/interfaces/swig/Machine.i, src/interfaces/swig/Regression.i, src/interfaces/swig/Regression_includes.i
#4463 
@gf712 @avramidis @vinx13 @shubham808 we need more of those
=> remove KRR from SWIG

src/shogun/CMakeLists.txt, src/shogun/lib/SGMatrix_benchmark.cc
This was added for examining if #4506 had any impact on the speed. See https://github.com/shogun-toolbox/shogun/pull/4506#pullrequestreview-200222124
=> Added SGMatrix benchmarks

doc/readme/INSTALL.md
correct typo in file INSTALL.md
=> correct typo

doc/readme/ABOUT.md
simple fix of typo I noticed in ABOUT.md documentation
=> fix typo in ABOUT.md

examples/undocumented/python/graphical/interactive_gp_demo.py, examples/undocumented/python/graphical/interactive_kmm_demo.py, examples/undocumented/python/graphical/interactive_svm_demo.py, examples/undocumented/python/graphical/interactive_svr_demo.py, examples/undocumented/python/kernel_combined_custom_poly.py, examples/undocumented/python/kernel_fisher.py, examples/undocumented/python/kernel_linear_string.py, examples/undocumented/python/kernel_poly.py, examples/undocumented/python/kernel_sparse_poly.py, examples/undocumented/python/kernel_top.py, examples/undocumented/python/mkl_binclass.py, examples/undocumented/python/mkl_multiclass.py, examples/undocumented/python/modelselection_grid_search_krr.py, examples/undocumented/python/serialization_string_kernels.py, src/interfaces/swig/Kernel.i, src/interfaces/swig/Kernel_includes.i
removed sg.PolyKernel in favour of sg.kernel("PolyKernel") factory
=> removed polykernel from swig

src/shogun/multiclass/tree/C45TreeNodeData.h, src/shogun/multiclass/tree/CARTreeNodeData.h, src/shogun/multiclass/tree/CHAIDTreeNodeData.h, src/shogun/multiclass/tree/ConditionalProbabilityTree.cpp, src/shogun/multiclass/tree/ConditionalProbabilityTree.h, src/shogun/multiclass/tree/ConditionalProbabilityTreeNodeData.h, src/shogun/multiclass/tree/ID3TreeNodeData.h, src/shogun/multiclass/tree/NbodyTreeNodeData.h, src/shogun/multiclass/tree/RelaxedTree.cpp, src/shogun/multiclass/tree/RelaxedTreeNodeData.h, src/shogun/multiclass/tree/TreeMachineNode.h
=> add treenode struct members to the tag framework

examples/meta/src/base_api/put_get_add.sg, examples/meta/src/statistical_testing/linear_time_maximum_mean_discrepancy.sg, examples/meta/src/statistical_testing/quadratic_time_maximum_mean_discrepancy.sg, src/interfaces/python/swig_typemaps.i, src/shogun/base/SGObject.cpp, src/shogun/base/SGObject.h, src/shogun/lib/DynamicObjectArray.h, src/shogun/statistical_testing/TwoSampleTest.cpp, src/shogun/statistical_testing/TwoSampleTest.h
***NO_CI***
@geektoni I will try to finish this tomorrow. Let me know if you have thoughts
=> [WIP] implementation of array SGObject::get

src/shogun/base/AnyParameter.h, src/shogun/features/SparseFeatures.cpp, src/shogun/lib/SGMatrix.cpp, src/shogun/lib/SGMatrix.h, src/shogun/lib/SGSparseVector.cpp, src/shogun/lib/SGSparseVector.h, src/shogun/lib/SGVector.cpp, src/shogun/lib/SGVector.h, src/shogun/util/iterators.h
because having to string is good in repl of interfaces.
=> to_string some class

doc/cookbook/source/index.rst
=> A quick typo fix

src/shogun/util/converters.h
realised there is a typo @vigsterkr
=> isfinite for msvc 2.0

doc/readme/INSTALL.md
Here comes the modification for #4588
=> Update INSTALL.md for compiling manually

src/shogun/lib/SGMatrix.cpp
=> Fix matrix string

examples/meta/generator/targets/cpp.json, examples/meta/generator/targets/python.json, examples/meta/src/observers/least_angle_regression.sg, examples/meta/src/observers/least_angle_regression_observable.sg, examples/undocumented/python/evaluation_cross_validation_mkl_weight_storage.py, src/interfaces/python/swig_typemaps.i, src/interfaces/swig/SGBase.i, src/interfaces/swig/shogun.i, src/shogun/base/SGObject.cpp, src/shogun/base/SGObject.h, src/shogun/regression/LeastAngleRegression.cpp, src/shogun/regression/LeastAngleRegression.h, tests/unit/regression/lars_unittest.cc
* Remove getters/setters from LARS;
* Make LARS observable;
* Add a meta example for the observable version;
* Add `get_long_int` to the meta language (aka `get<int64_t>()`);
=> Make LARS observable.

src/shogun/classifier/LDA.cpp, src/shogun/classifier/LDA.h, tests/unit/classifier/LDA_unittest.cc
* Removed getter and setters in favour of the `get`/`put` architecture;
* Use `put()` to set weights and bias;
* Correct LDA unit tests;
=> Refactor LDA classifier to make it more "observable".

src/shogun/features/DotFeatures.cpp, tests/unit/features/DotFeatures_unittest.cc
This fixes a buffer underflow bug in `dense_dot_range`.
=> Fix bug in dense_dot_range

doc/cookbook/source/examples/observers/least_angre_regression.rst, doc/cookbook/source/index.rst
* Add Observable Models section to the cookbook index page.
=> Add LARS cookbook example.

src/interfaces/swig/ParameterObserver.i, src/shogun/base/SGObject.cpp, src/shogun/base/SGObject.h, src/shogun/classifier/AveragedPerceptron.cpp, src/shogun/classifier/LDA.cpp, src/shogun/classifier/Perceptron.cpp, src/shogun/clustering/GMM.cpp, src/shogun/evaluation/CrossValidation.cpp, src/shogun/io/TBOutputFormat.cpp, src/shogun/lib/observers/ObservedValue.cpp, src/shogun/lib/observers/ObservedValue.h, src/shogun/lib/observers/ObservedValueTemplated.h, src/shogun/lib/observers/ParameterObserver.cpp, src/shogun/lib/observers/ParameterObserver.h, src/shogun/lib/observers/ParameterObserverCV.cpp, src/shogun/lib/observers/ParameterObserverCV.h, src/shogun/lib/observers/ParameterObserverHistogram.cpp, src/shogun/lib/observers/ParameterObserverLogger.cpp, src/shogun/lib/observers/ParameterObserverScalar.cpp, src/shogun/lib/observers/ParameterObserverTensorBoard.cpp, src/shogun/lib/observers/observers_utils.h, src/shogun/regression/LeastAngleRegression.cpp, tests/unit/io/TBOutputFormat_unittest.cc, tests/unit/lib/observers/ObservedValue_unittest.cc
1. Move `ObservedValue`/`ObservedValueTemplated` out from `SGObject.h`;
2. Remove `observe()` from `put()` call;
3. Replace all the occurrencies of `put()` with `observe()` inside observable algorithms;
=> [WIP] Refactor again ObservedValue/ObservedValueTemplated and put()/observe().

src/shogun/base/AnyParameter.h, src/shogun/base/SGObject.h, tests/unit/base/MockObject.h, tests/unit/lib/Any_unittest.cc
these enums are not needed anymore
=> remove old enums from AnyParameterProperties

src/shogun/features/CombinedDotFeatures.cpp, src/shogun/features/CombinedDotFeatures.h, src/shogun/features/DotFeatures.cpp, src/shogun/features/DotFeatures.h, tests/unit/features/CombinedDotFeatures_unittest.cc
This is to reduce the state of DotFeatures, and for better abstraction.
=> Move feature weights to CombinedFeature class

src/shogun/CMakeLists.txt, src/shogun/base/SGObject.cpp, src/shogun/base/SGObject.h, src/shogun/base/init.cpp, src/shogun/lib/config.h.in, src/shogun/lib/memory.cpp, src/shogun/lib/memory.h
removed TRACE_MEMORY_ALLOCS from everywhere
=> remove TRACE_MEMORY_ALLOCS
