- tests/unit/mathematics/Statistics_unittest.cc
Caught while testing linalg native backend without eigen3/viennacl being present.
> Added missing HAVE_EIGEN3 guard in Statistics unittest

- src/interfaces/octave_static/OctaveInterface.cpp
- src/interfaces/r_static/RInterface.cpp
- src/shogun/io/File.cpp
Fixes one of the reasons for the issue #2380
> Use get_strdup instead of strdup to avoid cygwin crashes

- CMakeLists.txt
- src/shogun/io/CSVFile.cpp
- src/shogun/io/CSVFile.h
- src/shogun/io/File.cpp
- src/shogun/io/File.h
- src/shogun/io/UAIFile.cpp
- src/shogun/io/UAIFile.h
POSIX C and ANSI C differs in their support of the fdopen function.
Added cmake check and ifdef for these fdopen calls
Relates #2380
> Optional fdopen calls

- src/interfaces/modular/modshogun.i
This is needed with SWIG >= 3.0.5 on MacOSX because of conflicting macros in AssertMacros.h of Carbon-framework.  Won't cause harm on other distros.
> fix build of modular interfaces with SWIG 3.0.5 on MacOSX

- src/shogun/mathematics/linalg/internal/implementation/Max.h
- tests/unit/mathematics/linalg/Max_unittest.cc
@lambday @iglesias Max function for vectors is also available in CMath. We can remove it from CMath if we are adding it here after the C++11 issue is resolved.
> Add linalg max native implementation

- CMakeLists.txt
- src/.doxy2swig.py
- src/interfaces/r_modular/CMakeLists.txt
* failsafe fix for new CMake-policy CMP0053 introduced by CMake >= 3.1
* fix "Argument not separated from preceding token by whitespace." for R-modular
* fix doxy2swig to use "encoding='utf-8'" when opening files by default  
on e.g. Fedora there are encoding-errors when using Python 3.X
> fixes for CMake

- src/shogun/kernel/GaussianARDKernel.cpp
- src/shogun/kernel/GaussianARDKernel.h
- src/shogun/kernel/LinearARDKernel.cpp
- src/shogun/kernel/LinearARDKernel.h
- src/shogun/mathematics/linalg/internal/implementation/Add.h
- src/shogun/mathematics/linalg/internal/implementation/Max.h
- src/shogun/mathematics/linalg/internal/implementation/VectorSum.h
- src/shogun/mathematics/linalg/internal/modules/Core.h
- src/shogun/mathematics/linalg/internal/modules/Redux.h
- moved `add`, `max`, and `vector_sum` outside the `HAVE_LINALG_LIB` guard
- guarded `CLinearARDKernel` and `CGaussianARDKernel` with `HAVE_LINALG_LIB` instead of `HAVE_CXX11` since the linalg methods used there are still dependent on third party libs and are not available natively (yet).
> Fix for issue #2729

- src/shogun/mathematics/linalg/internal/implementation/Scale.h
- src/shogun/mathematics/linalg/internal/modules/Core.h
- tests/unit/mathematics/linalg/Scale_unittest.cc
towards #2717. Everything is not yet replaced.
> move scale to linalg

- src/shogun/kernel/LinearARDKernel.cpp
- src/shogun/machine/gp/EPInferenceMethod.cpp
- src/shogun/machine/gp/ExactInferenceMethod.cpp
- src/shogun/machine/gp/FITCInferenceBase.cpp
- src/shogun/machine/gp/FITCInferenceBase.h
- src/shogun/machine/gp/KLInferenceMethod.cpp
- src/shogun/machine/gp/MultiLaplacianInferenceMethod.cpp
- src/shogun/machine/gp/SingleFITCLaplacianBase.cpp
- src/shogun/machine/gp/SingleFITCLaplacianBase.h
- src/shogun/machine/gp/SingleLaplacianInferenceMethod.cpp
@karlnapf 
take a look at this.
There are some issues about fitc inference.
In order to efficiently implement fitc inference, I need to a method to compute diagonal elements of a kernel matrix and related gradients.
I can implement the method for GaussianARD kernel.
Since we have to support general kernels, I may need to modify/add a `init` method in `CKernel`.
> minor fix and comments about time complexity of fitc regression

- examples/undocumented/libshogun/so_multilabel.cpp
Also remove braces for one-liner for loops.
> Fix bug in so_multilabel libshogun example

- examples/undocumented/python_modular/kernel_sparse_poly_modular.py
- examples/undocumented/python_modular/tests_check_commwordkernel_memleak_modular.py
- src/shogun/evaluation/CrossValidationMulticlassStorage.cpp
- src/shogun/evaluation/MulticlassOVREvaluation.cpp
fix minor issues when building python_modular with "patched" swig 3.X
* fix failing test when building with swig 3.X
* fix segfault when calling delete[] twice on SGMatrix-instances
> fix segfaults when calling delete[] twice on SGMatrix-instances and fix minor issues with swig 3.X

- src/shogun/mathematics/linalg/internal/implementation/MatrixProduct.h
- src/shogun/mathematics/linalg/internal/modules/Core.h
- tests/unit/mathematics/linalg/MatrixProduct_unittest.cc
Bugfix for issue #2801. New addition :
- One new method for matrix_product in Core module that
doesn't support preallocated result parameter but rather
returns the result in a newly created matrix.
- Accompanying implementation in MatrixProduct
- Two new unit-tests in MatrixProduct_unittest
> Added backend-type/matrix-type independent matrix-product in linalg

- benchmarks/matrix_product_benchmark.cpp
- Compares the penalty for CPU/GPU data transfer
for Matrix-Matrix product.
- Uses a third party benchmarking toolkit (hayai),
available at https://github.com/nickbruun/hayai.
> Added a benchmark for linalg::matrix_product

- src/shogun/lib/SGMatrix.cpp
- src/shogun/lib/SGMatrix.h
- tests/unit/lib/SGMatrix_unittest.cc
- Both copy the refcount of the SGVector to make sure that memory
is not accidentally deleted. Therefore we don't have to turn off
refcount for the SGMatrix as well
> Added two constructors in SGMatrix with SGVectors

- examples/example-generation/translate.py
Change `translate.py` to use `argparse` for command line argument parsing like in `parse.py` and `generate.py`.
> Meta-language: Change command line parsing to using argparse

- src/shogun/io/SerializableJsonFile.cpp
This funct is deprecated since json-c >= 0.9, we need >=0.11.  So no problems are expected nor ifdefs.
> replace obsolete `json_object_object_get` with `json_object_object_get_ex`

- examples/undocumented/r_modular/CMakeLists.txt
As said by title.  Testsuite ran successfully local and on Fedora's koji-builders.
> obey $ENV{R_LIBS_USER} when running tests

- benchmarks/elementwise_benchmark.cpp
- src/shogun/lib/GPUMatrix.h
- src/shogun/lib/GPUVector.h
- src/shogun/lib/SGMatrix.h
- src/shogun/lib/SGVector.h
- src/shogun/mathematics/linalg/internal/implementation/ElementwiseUnaryOperation.h
- src/shogun/mathematics/linalg/internal/implementation/operations/Sin.h
- src/shogun/mathematics/linalg/internal/implementation/operations/opencl_operation.h
- src/shogun/mathematics/linalg/internal/implementation/util/AllocResultUtil.h
- src/shogun/mathematics/linalg/internal/modules/ElementwiseOperations.h
- src/shogun/mathematics/linalg/linalg.h
- tests/unit/mathematics/linalg/ElementwiseOperations_unittest.cc
- Works with predefined operations (sin, cos, log, exp etc.)
- Works with custom unary operators as well (functors, std::function, lambda expressions, function pointers) that developers can provide.
- Implicit type conversion is **turned off** for CPU to/from GPU matrix/vector data-types. NATIVE/EIGEN3 works only with SG-types and VIENNACL works only with CGPU-types.
- Type safety ensured.
- A benchmark of element-wise operation with a custom unary operator.
> Added element-wise unary operators in linalg

- src/shogun/io/SGIO.h
- src/shogun/neuralnets/NeuralNetwork.cpp
- src/shogun/neuralnets/NeuralNetwork.h
@lisitsyn Have a look. Currently I'm printing the max and mean gradients after each iteration. Something like: https://gist.github.com/sanuj/4994d1d8feccdf069400
> Add gradient output functionality in Neural Nets

- src/shogun/base/SGObject.cpp
- src/shogun/machine/gp/EPInferenceMethod.cpp
- src/shogun/machine/gp/EPInferenceMethod.h
- src/shogun/machine/gp/ExactInferenceMethod.cpp
- src/shogun/machine/gp/ExactInferenceMethod.h
- src/shogun/machine/gp/FITCInferenceMethod.cpp
- src/shogun/machine/gp/FITCInferenceMethod.h
- src/shogun/machine/gp/InferenceMethod.cpp
- src/shogun/machine/gp/InferenceMethod.h
- src/shogun/machine/gp/KLInferenceMethod.cpp
- src/shogun/machine/gp/KLInferenceMethod.h
- src/shogun/machine/gp/LaplacianInferenceBase.cpp
- src/shogun/machine/gp/LaplacianInferenceBase.h
- src/shogun/machine/gp/MultiLaplacianInferenceMethod.cpp
- src/shogun/machine/gp/SingleFITCLaplacianInferenceMethod.cpp
- src/shogun/machine/gp/SingleFITCLaplacianInferenceMethod.h
- src/shogun/machine/gp/SingleLaplacianInferenceMethod.cpp
- src/shogun/machine/gp/SingleLaplacianInferenceMethod.h
- tests/unit/base/SGObject_unittest.cc
- tests/unit/machine/gp/InferenceMethod_unittest.cc
> users can disable the gradient computation [new]

- src/shogun/mathematics/linalg/internal/implementation/Max.h
- src/shogun/neuralnets/NeuralConvolutionalLayer.cpp
- src/shogun/neuralnets/NeuralConvolutionalLayer.h
- tests/unit/neuralnets/NeuralNetwork_unittest.cc
PR for issue #2700 
@lisitsyn Please have a look. I'm not sure if this is the correct way to implement this.
> Implement new initializations for conv neuralnet layer

- CMakeLists.txt
Needed for hardening-flags in Fedora.  This policy will pass all compiler-flags to stuff like 'FIND_PACKAGE()'.  Introduced with CMake 3.2.0.
Shouldn't break any builds.
> enable CMake-policy CMP0056, if available

- src/shogun/machine/gp/GaussianARDSparseKernel.cpp
- src/shogun/machine/gp/GaussianARDSparseKernel.h
I rename the method to keep the method in the GP modular consistent
> rename init() method in GP

- src/shogun/optimization/ElasticNetPenalty.h
- src/shogun/optimization/FirstOrderStochasticMinimizer.h
- src/shogun/optimization/L1Penalty.h
- src/shogun/optimization/L1PenaltyForTG.h
- src/shogun/optimization/ProximalPenalty.h
- src/shogun/optimization/SGDMinimizer.cpp
- src/shogun/optimization/SMIDASMinimizer.cpp
- src/shogun/optimization/SVRGMinimizer.cpp
consider the following problem
`min f(x)+h(x)`
where 
* f(x) is convex, differentiable, `domain of f(x)=R^n`  
* h(x) is closed, convex, possibly non-differentiable
Proximal gradient method:
at iteration k+1
* x^{k+1/2} = x^{k} - learning_rate * d_f(x^{k})
* x^{k+1} = prox_h (x^{k+1/2}) 
where `prox_h` is a proximal penalty for `h(x)`
for example, `h(x)=L1_weight * |x|_1`
> support proximal gradient methods as proximal penalty

- src/shogun/neuralnets/NeuralNetwork.cpp
A very trivial typo. 
Changed: ">" to ">="
> Fixed typo in error message for gd_momentum range

- src/shogun/optimization/AdaDeltaUpdater.cpp
- src/shogun/optimization/AdaDeltaUpdater.h
- src/shogun/optimization/AdaGradUpdater.cpp
- src/shogun/optimization/AdaGradUpdater.h
- src/shogun/optimization/RmsPropUpdater.cpp
- src/shogun/optimization/RmsPropUpdater.h
- tests/unit/optimization/StochasticMinimizers_unittest.cc
Added parameterised constructors to the following classes:
* AdaDeltaUpdater
* AdaGradUpdater
* RmsPropUpdater
This will make initialising those objects in other classes easier. Another advantage of avoiding using the *set_xyz* functions explicitly is that they are not present in the DU class and hence, we can work with just a DU object that is actually cast from a subclass of it.
(I'm not sure if there is a way around it even without a param ctor)
I modified some of the unit tests to use the new constructors for testing.
> Added parameterized constructors to DescendUpdater derived classes

- NEWS
- tests/unit/CMakeLists.txt
In some cases gTest segfaults with GCC >= 6.0.0.  This is a dirty fix.
TODO: Update to gTest-release with proper support for GCC >= 6.0.0.
See:  https://github.com/google/googletest/issues/705
> fix gTest segfaults with GCC >= 6.0.0.

- examples/undocumented/python_modular/graphical/interactive_clustering_demo.py
- examples/undocumented/python_modular/graphical/interactive_gp_demo.py
- examples/undocumented/python_modular/graphical/interactive_kmm_demo.py
- examples/undocumented/python_modular/graphical/interactive_svm_demo.py
- examples/undocumented/python_modular/graphical/interactive_svr_demo.py
- examples/undocumented/python_modular/graphical/kernel_ridge_regression.py
- examples/undocumented/python_modular/graphical/kernel_ridge_regression_sinc.py
- examples/undocumented/python_modular/graphical/lda.py
- examples/undocumented/python_modular/graphical/mclda.py
- examples/undocumented/python_modular/graphical/multiple_smvs.py
- examples/undocumented/python_modular/graphical/qda.py
- examples/undocumented/python_modular/graphical/regression_gaussian_process_demo.py
- examples/undocumented/python_modular/graphical/so_multiclass_BMRM.py
- examples/undocumented/python_modular/graphical/so_multiclass_director_BMRM.py
- examples/undocumented/python_modular/graphical/svm.py
- examples/undocumented/python_modular/graphical/svmlin.py
- examples/undocumented/python_modular/graphical/svr_sinc.py
Most of the examples were working except the following:
`so_multiclass_director_BMRM.py`:
```
ImportError: cannot import name DirectorStructuredModel
```
`so_multiclass_BMRM.py`:
```
Traceback (most recent call last):
File "so_multiclass_BMRM.py", line 78, in <module>
plt.plot(xrange(res.get_n_iters()), Fps, hold=True)
File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3154, in plot
ret = ax.plot(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1812, in inner
return func(ax, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 1424, in plot
for line in self._get_lines(*args, **kwargs):
File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 386, in _grab_next_args …
```
> cleanup python modular graphical examples

- doc/ipython-notebooks/regression/Regression.ipynb
Removes a deprecated warning and three errors. This notebook has been saved for version 4 of ipython since i have that installed on my laptop.
@karlnapf I wanted to confirm whether version 4 is ok for shogun or should i stick to version 3 (that shogun uses currently) before I send anymore notebook related PRs.
> clean up regression notebook

- src/shogun/classifier/svm/LibLinear.cpp
- src/shogun/machine/LinearMachine.cpp
- src/shogun/machine/LinearMachine.h
- src/shogun/regression/LinearRidgeRegression.cpp
- src/shogun/regression/LinearRidgeRegression.h
- tests/unit/regression/LinearMachine_unittest.cc
@karlnapf  check changes for issue #3033 :
1- Replace `lapack` calls in `CLinearRidgeRegression::train_machine()` by `eigen` calls.
2- Add `bias_flag` to `LinearMachine` class
3- Add `compute_bias()` method to `LinearMachine` class
4- Override `train()` to add optional `compute_bias()`
> Add automatic bias computation in LinearMachine

- examples/undocumented/libshogun/so_multiclass_BMRM.cpp
- examples/undocumented/python_modular/regression_cartree_modular.py
- examples/undocumented/python_modular/statistics_hsic.py
- examples/undocumented/python_modular/structure_graphcuts.py
- examples/undocumented/python_modular/structure_plif_hmsvm_bmrm.py
- tests/unit/base/RefCount_unittest.cc
For #3005.
I haven't touched those that use shogun-data. Final output of `make test` after changes is [here](https://gist.github.com/sanuj/36dbf0ff8af9de9c8468).
> Shorten time and diagnose failing python modular examples.

- src/shogun/machine/LinearMachine.cpp
@karlnapf 
I compiled and there were no warnings.
I am using gcc  4.8.4
> Avoid compiler warnings in LinearMachine

- examples/descriptions/modular/classifier_knn.txt
- examples/meta/CMakeLists.txt
- tests/meta/CMakeLists.txt
since they use the auto keyword (and there is not other way to infer types in the meta language with reasonable effort)
> only do c++ meta examples if c++11 is available

- src/shogun/distance/Distance.h
- src/shogun/distance/EuclideanDistance.cpp
- src/shogun/distance/EuclideanDistance.h
- tests/unit/distance/EuclideanDistance_unittest.cc
Adding precompute to base distance to overload in sub class.
Discussed in PR https://github.com/shogun-toolbox/shogun/pull/3067 based on https://github.com/shogun-toolbox/shogun/issues/2987
> add precompute to base Distance

- examples/meta/cpp/CMakeLists.txt
- examples/meta/csharp/CMakeLists.txt
- examples/meta/java/CMakeLists.txt
- examples/meta/lua/CMakeLists.txt
- examples/meta/octave/CMakeLists.txt
- examples/meta/python/CMakeLists.txt
- examples/meta/r/CMakeLists.txt
- examples/meta/ruby/CMakeLists.txt
- tests/meta/CMakeLists.txt
http://buildbot.shogun-toolbox.org/builders/FC22%20-%20libshogun/builds/150/steps/test/logs/stdio
Avoid using REGEXP for untangling filenames in meta examples, but rather leave this to cmake. Hoping this fixes the problem on buildbot
> fix FC22 buildbot (hopefully)

- src/shogun/clustering/KMeans.cpp
- src/shogun/clustering/KMeans.h
- src/shogun/clustering/KMeansLloydImpl.cpp
- src/shogun/clustering/KMeansLloydImpl.h
- src/shogun/distance/Distance.h
- tests/unit/clustering/kmeans_unittest.cc
This has most of the primary changes to Kmeans based on https://github.com/shogun-toolbox/shogun/issues/2987 and some general cleanups.
Still have to do some aesthetic changes.
- Changed random initialization
- now chooses `k` random points as centers rather than assigning random centers to all points.
- Removed unnecessary paramters, cluster_list, weight_set, etc. This should be calculated in the Lloyds implementation.
- changed manual initialization
- again Removed unnecessary paramters
- removed calculation of  distances and assigning of clusters from here, this along wth the parameters now takes place in assignment step of lloyds.
- made clear separation for assigment step and update step in lloyds impl.
- removed random sampling of instances to be updated in each iteration, each …
> kmeans update

- src/shogun/multiclass/QDA.cpp
Removing the unnecessary transpose enhances Shogun's performance to be same as scikit-learn.
check this [notebook](https://github.com/youssef-emad/shogun_notebooks/blob/master/QDA.Investigation.ipynb) for results before and after modification.
> Remove transpose of rotations in QDA

- src/shogun/regression/KernelRidgeRegression.cpp
- src/shogun/regression/KernelRidgeRegression.h
For #3095. KRR uses Eigen3's LLT now.
I haven't added any unit tests as other regression unit tests have taken reference data from some other ml toolbox. Shall I also prepare small data and run it on scikit learn to use it's results in our unit tests?
Apart from that, there are 2 tests related to KRR. One is `generated_cpp-kernel_ridge_regression` and the other one is `evaluation_cross_validation_regression`. Both are passing.
> trian krr by using eigen3 llt

- src/shogun/mathematics/linalg/internal/implementation/MeanEigen3.h
- src/shogun/mathematics/linalg/internal/modules/Redux.h
- tests/unit/mathematics/linalg/MeanEigen3_unittest.cc
To make things less messy I put this part in a new branch so I opened a new PR. Ref #3085,  #3070 and issue #3051 .
Simple implementation - return vector mean `decltype(vector data type) vector mean` for Eigen3.
Seems I can add both `Vector` and `Matrix` to `Matrix` template?
> Implement Vector Mean in linalg

- src/shogun/mathematics/Statistics.cpp
- tests/unit/mathematics/Statistics_unittest.cc
@karlnapf sending a PR because I wanted you to have a look. `erfc(...)` is a C-function so no C++11 is needed for this one.
> added normal_cdf

- examples/meta/generator/targets/ruby.json
@karlnapf Couldn't build it on my local. Got this error:
```
Linking CXX shared module modshogun.so
/usr/bin/ld: /usr/local/lib/libruby-static.a(array.o): relocation R_X86_64_PC32 against symbol `rb_ary_free' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```
> fix enum rule for ruby

- examples/meta/generator/targets/ruby.json
Correct syntax for enums in Ruby
> Meta-Language: Fix ruby enum rule

- examples/meta/generator/targets/lua.json
I think this is the last one. The enums have already been tested in Python, R, Octave, and Java.
> Meta-Language: Fix Lua enum rule

- src/shogun/mathematics/linalg/internal/implementation/MeanEigen3.h
- src/shogun/mathematics/linalg/internal/modules/Redux.h
- tests/unit/mathematics/linalg/MeanEigen3_unittest.cc
Refer #3051 and PR #3070 
An issue with current solution is one has to have `no_diag` parameter when computing the mean of a matrix. 
Maybe a better way is to map `vector` to `matrix` in `Redux.h`?
Also I am wondering maybe the test file is too long.
> Add matrix_mean in linalg using Eigen3

- src/shogun/mathematics/linalg/internal/implementation/MeanEigen3.h
- src/shogun/mathematics/linalg/internal/modules/Redux.h
- tests/unit/mathematics/linalg/MeanEigen3_unittest.cc
Refer #3051 and PR #3070, #3125 
- I didn't implement `colwise_mean` at the same time because I'm not sure how this implement looks like. Apparently I cannot copy `SGVector<T>` to `SGVector<int2float type>` so I just used `for`-loops. Also, I think we are supposed to use EIGEN3 methods, which I have not tried (but used `for`-loop instead). 
- According to #3100, I think we can get rid of `<enum Backend>` generic type? I can re-factor this after `rowwise`/`colwise` are both done.
- There are also `Block` and `symmetric matrix` calculation for `matrixsum`. I am wondering whether we need both for `matrixmean` as while?
- I saw the comparison highlighted the changes I made in PR #3125 (merged). I had no idea why this is happening...
> Add rowwise_mean to linalg using Eigen3

- src/shogun/mathematics/linalg/internal/implementation/Cholesky.h
- tests/unit/mathematics/linalg/Cholesky_unittest.cc
fix for the failing build with viennacl backend : http://buildbot.shogun-toolbox.org/builders/trusty%20-%20libshogun%20-%20viennacl/builds/616
I have also opened issue #3156 regarding the general handling of viennacl backend by methods that don't have their viennacl backends implemented in linalg yet.
also, a minor change for the compute method to use the general ReturnType instead of SGMatrix
> explicitly mentioned eigen3 backend in Cholesky_unittest and a minor change in Cholesky.h

- src/shogun/machine/gp/KLDualInferenceMethod.h
- src/shogun/optimization/lbfgs/LBFGSMinimizer.h
- src/shogun/optimization/lbfgs/lbfgs.h
@karlnapf 
The compiler in the precise build does not support `enum` class.
> fix an issue related to enum class for the precise build

- examples/undocumented/python_modular/modelselection_parameter_tree_modular.py
- src/shogun/modelselection/ParameterCombination.h
Iterating through parameter combinations in python as indicated in `modelselection_parameter_tree_modular.py` doesn't work since `get_element()` returns a `CSGObject` pointer.
This patch adds an `obtain_from_generic()` function to `CParamterCombination` that performs the type cast. The example was adopted.
> Implement CParameterCombination::obtain_from_generic()

- src/shogun/lib/external/cdflib.cpp
- src/shogun/lib/external/cdflib.hpp
[This PR fixes the following warnings](http://buildbot.shogun-toolbox.org/builders/deb3%20-%20modular_interfaces/builds/2853/steps/libshogun/logs/warnings%20(10)/text)
```
/home/buildslave/deb3_-_modular_interfaces/build/src/shogun/lib/external/cdflib.cpp:2223:36: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
/home/buildslave/deb3_-_modular_interfaces/build/src/shogun/lib/external/cdflib.cpp:3909:20: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
/home/buildslave/deb3_-_modular_interfaces/build/src/shogun/lib/external/cdflib.cpp:6924:17: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
/home/buildslave/deb3_-_modular_interfaces/build/src/shogun/lib/external/cdflib.cpp:6946:18: warning: suggest parentheses around ‘&&’ within …
```
> Fix cdflib warnings for libshogun build

- src/shogun/classifier/LDA.h
- src/shogun/distance/EuclideanDistance.h
- src/shogun/mathematics/Statistics.h
- src/shogun/mathematics/linalg/internal/implementation/MeanEigen3.h
- src/shogun/mathematics/linalg/internal/implementation/Sum.h
- src/shogun/neuralnets/RBM.h
- src/shogun/preprocessor/FisherLDA.h
- src/shogun/preprocessor/PCA.h
- src/shogun/statistics/NOCCO.h
Fix some warnings from [here](http://buildbot.shogun-toolbox.org/builders/deb3%20-%20modular_interfaces/builds/2853/steps/python%20modular/logs/warnings%20(87)/text).
> Fix some documentation warnings in python mod build

- CMakeLists.txt
@vigsterkr UPDATE: I applied the fix to develop as it is definitely necessary. The rest is optional for cleaner cmake options.
I renamed them to start with LINALG_ so that they are grouped if ppl check the options and not scattered all over without it being clear that they change linag behaviour. Also, ccmake which shows the cached options now does't show a binary ON/OFF, but the string. Just like CMAKE_BUILD_TYPE
This might interfere with some builds. Let me know
> eigen3 correction

- src/shogun/clustering/KMeans.cpp
- src/shogun/clustering/KMeans.h
- tests/unit/clustering/kmeans_unittest.cc
@OXPHOS The old kmeans methods for some reason were ruby unfriendly. I rename them here, after which the ruby example works for me locally. You have to rebase after merge and then adjust the kmeans method calls in your example #3183
> renamed kmeans methods to be ruby friendly

- examples/meta/generator/parse.py
@OXPHOS this allows to use
`int variable = 0` in the meta language
> fix meta example language to allow the "0" literal

- src/shogun/clustering/KMeansLloydImpl.h
- src/shogun/lib/external/cdflib.cpp
- src/shogun/machine/LinearMachine.h
- src/shogun/mathematics/linalg/internal/implementation/ElementwiseSquare.h
- src/shogun/mathematics/linalg/internal/implementation/MeanEigen3.h
- src/shogun/neuralnets/RBM.h
- src/shogun/statistics/NOCCO.h
Fixes following warnings:
```
/home/buildslave/deb3_-_modular_interfaces/build/src/shogun/lib/external/cdflib.cpp:10864:20: warning: variable ‘tm’ set but not used [-Wunused-but-set-variable]
/home/buildslave/deb3_-_modular_interfaces/build/src/shogun/clustering/KMeansLloydImpl.h:26: warning: argument 'ClList' of command @param is not found in the argument list of shogun::CKMeansLloydImpl::Lloyd_KMeans(int32_t k, CDistance *distance, int32_t max_iter, SGMatrix< float64_t > mus, bool fixed_centers)
/home/buildslave/deb3_-_modular_interfaces/build/src/shogun/clustering/KMeansLloydImpl.h:26: warning: argument 'weights_set' of command @param is not found in the argument list of shogun::CKMeansLloydImpl::Lloyd_KMeans(int32_t k, CDistance *distance, int32_t max_iter, SGMatrix< float64_t > mus, …
```
> fix modshogun and python warnings

- src/shogun/evaluation/GradientResult.h
Fixes #3211 Invalid use of incomplete type ‘struct shogun::TParameter’
> Fixes #3211 Invalid use of incomplete type ‘struct shogun::TParameter’

- src/shogun/mathematics/Statistics.h
- src/shogun/mathematics/linalg/internal/implementation/ElementwiseSquare.h
- src/shogun/mathematics/linalg/internal/implementation/MeanEigen3.h
- src/shogun/mathematics/linalg/internal/implementation/Sum.h
Is this the correct way to do it? - 
Fixed documentation warnings in `mathematics/` in http://buildbot.shogun-toolbox.org/builders/deb3%20-%20modular_interfaces/builds/2853
> Fix buildbot mathematics/ warnings

- configs/valgrind.supp
Some suppression for unnecessary  memcheck warnings with openmp.
pls do NOT merge yet.
> suppression for memcheck openmp

- benchmarks/linalg_refactor_benchmark.cpp
- compare CPU.dot and GPU.dot of current linalg and refactored linalg
- ref #3230 
- cannot use global variable: `sg_linalg` (segmentation fault 11)
> Linalg benchmark

- src/shogun/distance/TanimotoDistance.h
This fixes #3261 Error in LaTeX formula for TanimotoDistance.
> Fixes #3261 Error in LaTeX formula for TanimotoDistance.

- cmake/FindSphinx.cmake
This fixes #3231 Cookbook generation error using Sphinx from PyPI.
Sphinx installed via PyPI resides in /usr/loca/bin
> Fixes #3231 Cookbook generation error using Sphinx from PyPI.

- examples/meta/generator/parse.py
This Fixes #3254 Cookbook generation crashes using empty meta example files.
> Fixes #3254 Cookbook generation crashes using empty meta example files.

- examples/meta/generator/generate.py
This fixes #3253 Cookbook generation failure missing responsible file indicator.
> Fixes #3253 Cookbook generation failure missing file indicator

- src/shogun/regression/LeastAngleRegression.cpp
- src/shogun/regression/LeastAngleRegression.h
- tests/unit/regression/lars_unittest.cc
> Lars update

- examples/meta/.gitignore
- examples/meta/generator/generate.py
- examples/meta/generator/parse.py
- examples/meta/generator/targets/cpp.json
- examples/meta/generator/targets/csharp.json
- examples/meta/generator/targets/java.json
- examples/meta/generator/targets/lua.json
- examples/meta/generator/targets/octave.json
- examples/meta/generator/targets/python.json
- examples/meta/generator/targets/r.json
- examples/meta/generator/targets/ruby.json
- examples/meta/generator/translate.py
- examples/meta/generator/types/get_type_list.sh
> Meta language: Modified parser to handle SGVector, SGMatrix accessing

- src/shogun/base/SGObject.h
- src/shogun/lib/any.h
- src/shogun/lib/basetag.h
- tests/unit/lib/Any_unittest.cc
Includes updates for latest review of #3221 and a small bug fix which I found while testing for SWIG interface.
> change method names, fix bug and docs

- cmake/FindMetaExamples.cmake
Fix for [this](http://buildbot.shogun-toolbox.org/builders/nightly_none/builds/1036/steps/compile/logs/stdio).
> add cmake guard for mkl regression cookbook

- src/shogun/classifier/mkl/MKL.cpp
- src/shogun/classifier/mkl/MKL.h
this way one will not require to supply the compiler flags
for GLPK or CPLEX when using MKL.
> Hide GPLK or CPLEX parameters

- src/shogun/multiclass/tree/CHAIDTree.cpp
The only situation I can think of that will result in `current=NULL` is one applies the machine to data without training.
> add assertation in CHAID tree

- src/shogun/lib/any.h
- tests/unit/lib/Any_unittest.cc
This would enable us to implement SG_ADD so that
parameters are used through map
and member variables at the same time.
> Add non-owning Any policy

- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgBackendViennacl.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
- tests/unit/mathematics/linalg/operations/Viennacl_operations_unittest.cc
Ref #3387
- I was trying to merge `void add` and `SGVector<T> add` into one method by doing ` template <typename T> auto add(SGVector<T>& a, SGVector<T>& b, T alpha=1, T beta=1, bool inplace=false) -> decltype((!inplace, SGVector<T>>))`, but I got error `expected ')' -> decltype((!inplace, SGVector<T>>))`. Not sure whether this is a solvable problem or whether there's other way to do it @vigsterkr 
- `TEST(LinalgBackendViennaCL, add_in_place)` is working well(`EXPECT_NEAR` are true), but I got error: `shogun-unit-test(9457,0x7fff7166a300) malloc: *** error for object 0x7f8a138c3590: pointer being freed was not allocated` at the end. I don't know which object was freed twice. 
- I think `add(A, B, alpha, beta, inplace=T)`  is more concise than `add(A, B, A, alpha, beta)` for in-place …
> LinalgRefactor -  SGVector - inplace add

- examples/meta/generator/targets/java.json
Part of making enum typed variables work in the meta language. We want the statement `LIBLINEAR_SOLVER_TYPE myVar = enum LIBLINEAR_SOLVER_TYPE.L2R_L2LOSS_SVC` to translate and work in all languages.
Related to #3390
> Meta-language: Cleaner import statements for enums in java

- examples/meta/generator/parse.py
- examples/meta/generator/targets/cpp.json
- examples/meta/generator/targets/csharp.json
- examples/meta/generator/targets/java.json
- examples/meta/generator/targets/lua.json
- examples/meta/generator/targets/octave.json
- examples/meta/generator/targets/python.json
- examples/meta/generator/targets/r.json
- examples/meta/generator/targets/ruby.json
- examples/meta/generator/translate.py
We need to specify precision of floating point literals because C# is very strict about downcasting these.
Fixes problem in #3390
> Split number literals into int, real (64bit float), and float literals

- examples/meta/src/binary_classifier/kernel_svm.sg
- examples/meta/src/binary_classifier/linear_svm.sg
- examples/meta/src/gaussian_processes/gaussian_process_classifier.sg
- examples/meta/src/gaussian_processes/gaussian_process_regression.sg
- examples/meta/src/meta_api/matrix_types.sg
- examples/meta/src/meta_api/vector_types.sg
- examples/meta/src/multiclass_classifier/svm.sg
- examples/meta/src/neural_nets/feedforward_net_regression.sg
- examples/meta/src/regression/kernel_ridge_regression.sg
- examples/meta/src/regression/multiple_kernel_learning.sg
- examples/meta/src/regression/support_vector_regression.sg
These changes were originally part of #3410
I have split this into another PR since it's a slightly tricky merge. This PR will only pass once  #3410 and shogun-toolbox/shogun-data#121 are merged. Note that merging the new integration test data will temporarily make the tests fail until this PR is merged.
> Fix literal types of meta examples

- examples/undocumented/python_modular/tags_params_modular.py
- src/interfaces/modular/shogun-base.i.jinja2
@vigsterkr Here we go. :beers:
> replace setsX("name", obj_X) by sets("name", obj_X)

- src/shogun/base/SGObject.cpp
- src/shogun/lib/SGReferencedData.cpp
- src/shogun/lib/SGVector.cpp
- tests/unit/io/CerealObject.h
- tests/unit/io/Cereal_unittest.cc
- Improved `CCerealObject` for more concise unittest
- Added `cereal::nvp` to some `save` methods for the readability.
Now the JSON serialization output of `CCerealObject` would be:
```
{
"CerealObject": {
"test_vector": {
"value0": 2,
"value1": 12,
"value2": {
"ReferencedData": {
"ref_counting": true,
"refcount number": 3
},
"length": 5,
"value0": 0,
"value1": 1,
"value2": 2,
"value3": 3,
"value4": 4
}
}
}
}
```
@vigsterkr
> Cereal serialization - Minor updates on unittests and cereal::nvps

- .gitignore
- examples/README
- examples/meta/generator/generate.py
- examples/meta/generator/targets/java.json
- examples/meta/generator/targets/javascript.json
- examples/meta/generator/translate.py
Added .gitignore entries for IntelliJ and VSCode;
Javascript (ES2015) meta description, for *Vector and *Matrix inits;
scijs ndarray dependency added;
meta def + translate.py prepared to handle <, >-type matrix definitions;
> Javascript support added to meta_examples

- src/interfaces/modular/Regression.i
- src/interfaces/modular/Regression_includes.i
Had to place SWIG lines after KernelRidgeRegression, since it is a parent class.
> Modular support for nystrom class

- examples/meta/generator/targets/csharp.json
- examples/meta/generator/targets/doc.js
- examples/meta/generator/translate.py
Adds interface for translations of element getters/setters on specific vector and matrix types. E.g. a `BoolVector` can now have a separate translation rule from all other vector types.
This change requires the translation code to keep track of the type of initialised objects. I have therefore also added some basic type checking assertions on assignments and method calls. This may help catch typos etc when writing meta examples.
> Meta csharp bool vector

- README.md
I was installing shogun recently and found that 
doc/readme/INSTALL.md  pointed at the wrong location.
> Correct the link  doc/readme/INSTALL.md points at

- doc/cookbook/source/examples/distance/cosine.rst
- examples/meta/src/distance/cosine.sg
Added **cosine.sg** and **cosine.rst** to create meta examples for distance-cosine and generated cookbook for distance-cosine.
> Add cosine-distance meta example

- src/shogun/kernel/string/CommUlongStringKernel.cpp
CommUlongStringKernel was producing "Done." messages on the console
> Fix Debug msg that was not continued to debug output

- src/shogun/classifier/AveragedPerceptron.cpp
- src/shogun/classifier/Perceptron.cpp
- src/shogun/classifier/mkl/MKLMulticlass.cpp
- src/shogun/classifier/svm/MPDSVM.cpp
- src/shogun/classifier/svm/NewtonSVM.cpp
- src/shogun/classifier/vw/VowpalWabbit.cpp
> Modify src/shogun/classifier/ to implement CSignal in outer loops

- tests/unit/lib/SGSparseMatrix_unittest.cc
Adding a test for transposing a square `SGSparseMatrix`.
#2748
> Test for transposing Square SGSparseMatrix.

- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
- tests/unit/mathematics/linalg/operations/Viennacl_operations_unittest.cc
The old Viennacl SGMatrix max test may cause segmentation fault
> LinalgRefactor - minor fix on linalg::max unittest

- src/shogun/lib/SGMatrix.cpp
- src/shogun/lib/SGMatrix.h
- src/shogun/lib/SGVector.cpp
- src/shogun/lib/SGVector.h
- tests/unit/lib/SGMatrix_unittest.cc
- add `assert_on_gpu()` 
- add `on_gpu()` check for elementwise (static) methods
However, the `gpu_ptr` is not serialized. I assume it's users' responsibility to transfer the data back to CPU before serialization. If so, I can add warnings or errors msg to `SGMatrix` serialization methods.
> LinalgRefactor - gpu_ptr compatibility in SGMatrix and SGVector

- tests/unit/CMakeLists.txt
- tests/unit/features/StreamingDenseFeatures_unittest.cc
- tests/unit/features/StreamingSparseFeatures_unittest.cc
- tests/unit/io/SerializationAscii_unittest.cc.jinja2
- tests/unit/io/SerializationXML_unittest.cc.jinja2
- tests/unit/utils/Utils.cpp
- tests/unit/utils/Utils.h
* ```make unit-tests``` was pointing to a wrong location of ```shogun-unit-test```
* Replaced mktemp with mktemp_cst to avoid many compiler warnings (see https://travis-ci.org/shogun-toolbox/shogun/jobs/202296293), since mktemp is not safe to use (and there is no way to suppress them, apparently).
> Fix `make unit-tests` and replace mktemp inside unit tests with a custom method

- src/shogun/multiclass/BruteKNNSolver.h
- src/shogun/multiclass/CoverTreeKNNSolver.h
- src/shogun/multiclass/KDTreeKNNSolver.h
- src/shogun/multiclass/KNNSolver.h
- src/shogun/multiclass/LSHKNNSolver.h
This pr is about fixing language error and fluffy comments in this pr https://github.com/shogun-toolbox/shogun/pull/3608. For more information, see @karlnapf 's comments in  https://github.com/shogun-toolbox/shogun/pull/3608#pullrequestreview-22316735
> clean up language error and fluffy comments

- src/shogun/evaluation/CrossValidation.cpp
- src/shogun/evaluation/CrossValidation.h
Would be great to see this back in develop
> Reintegrate parallel crossvalidation

- src/shogun/multiclass/KDTreeKNNsolver.cpp
- tests/unit/multiclass/KNN_unittest.cc
I found unit test for kdtree actually is using `KNN_BRUTE` as solver type https://github.com/shogun-toolbox/shogun/blob/develop/tests/unit/multiclass/KNN_unittest.cc#L94 and https://github.com/shogun-toolbox/shogun/blob/develop/tests/unit/multiclass/KNN_unittest.cc#L186. And it seems like we missing unit test for covertree solver. 
When I working on the test for kdtree, I found a minor error for the `classify_for_multiple_k` of kdtree. So this pr is for these things I mentioned above. Please take a look at this. Thank you :)
> add tests for KNN and fix an error in KDTree solver

- cmake/FindMetaExamples.cmake
- doc/cookbook/CMakeLists.txt
This should fix issue #3520. These changes fix also ``` make cookbook_sphinx_linkcheck```.
The command ```make cookbook``` still gives me warnings, though, but I don't understand if they are caused by my changes or if they were already there.
See warnings here: http://pastebin.com/chxfGvaq
> Fix `make cookbook` when certain cookbooks are guarded

- src/shogun/multiclass/BruteKNNSolver.cpp
- src/shogun/multiclass/BruteKNNSolver.h
- src/shogun/multiclass/CoverTreeKNNSolver.cpp
- src/shogun/multiclass/CoverTreeKNNSolver.h
- src/shogun/multiclass/KDTreeKNNSolver.h
- src/shogun/multiclass/KDTreeKNNsolver.cpp
- src/shogun/multiclass/KNN.cpp
- src/shogun/multiclass/KNNSolver.h
- src/shogun/multiclass/LSHKNNSolver.cpp
- src/shogun/multiclass/LSHKNNSolver.h
This pr is about to fix the warning generated by  **shadow declaration of ‘distance’**  in KNNSolvers. For example, as @vigsterkr pointed out on irc, 
>
> /home/wiking/shogun/src/shogun/multiclass/KDTreeKNNsolver.cpp: In member function ‘virtual shogun::CMulticlassLabels* shogun::CKDTREEKNNSolver::classify_objects(shogun::CDistance*, int32_t, int32_t*, float64_t*) const’:
> /home/wiking/shogun/src/shogun/multiclass/KDTreeKNNsolver.cpp:20:139: warning: declaration of ‘distance’ shadows a member of 'this' [-Wshadow]
> CMulticlassLabels* CKDTREEKNNSolver::classify_objects(CDistance* distance, const int32_t num_lab, int32_t* train_lab, float64_t* classes) const
>
BTW, I guess this pr may conflict with another pr also related with KNN https://github.com/shogun-toolbox/shogun/pull/3641. Please …
> Use SGVector instead of pointer in KNN solvers and fix the warning when building KNNSolvers

- src/shogun/features/Alphabet.cpp
- src/shogun/features/Alphabet.h
- tests/unit/features/Alphabet_unittest.cc
Seems like `CAlphabet` couldn't be cloned properly. Another bug that surfaced with the all the cloning happening now with parallel xval, for me in the case of `CCommWordStringKernel`.
There are some remarks about this in the serialization section [here](https://github.com/shogun-toolbox/shogun/blob/develop/src/shogun/features/Alphabet.cpp#L721).
Please check.
> Fix CAlphabet::Clone + unit test

- tests/unit/mathematics/linalg/LinalgBackendViennaCL_unittest.cc
I don't think I describe the test correctly - the variable is assigned to another chunk of memory after the operation. This is the scenario where mutex is required for memory transfer methods as mentioned in #3635
> LinalgRefactor - add "in_place" memory transfer test

- src/shogun/clustering/KMeans.cpp
- src/shogun/features/DenseFeatures.cpp
- src/shogun/features/DenseFeatures.h
@karlnapf turns out, clone was required (one unit-test failed otherwise). So, put the cloning responsibility in the caller.
> Removed copy_feature_matrix method from DenseFeatures

- src/shogun/base/Parameter.cpp
- tests/unit/features/StringFeatures_unittest.cc
`StringFeatures<T>` contain an `SGString<T>*` parameter that caused `::clone()` on the features to fail.
IMHO this fixes `TParameter::copy()`, however, I'm not familiar with this code, so please check (see inline comments)
> Fix TParameter copy

- src/shogun/base/SGObject.h
- src/shogun/kernel/DirectorKernel.h
Classes `ParameterMap` and `SGParamInfo` have been removed.
Methods `CSGObject::migrate()` and `CSGObject::one_to_one_migration_prepare()` have been removed.
> Clean up SGObject import and DirectorKernel methods

- src/shogun/io/SGIO.cpp
See #3509.
**SG_PROGRESS current behaviour**:
**SG_PROGRESS patch behaviour**:
> Fix wrong behaviour of SGIO::progress

- src/shogun/classifier/AveragedPerceptron.cpp
- src/shogun/classifier/FeatureBlockLogisticRegression.cpp
- src/shogun/classifier/LDA.cpp
- src/shogun/classifier/Perceptron.cpp
- src/shogun/classifier/svm/LibLinear.cpp
- src/shogun/classifier/svm/LibLinear.h
- src/shogun/classifier/svm/SGDQN.cpp
- src/shogun/classifier/svm/SVMOcas.cpp
- src/shogun/classifier/svm/SVMOcas.h
- src/shogun/classifier/svm/SVMSGD.cpp
- src/shogun/latent/LatentSOSVM.cpp
- src/shogun/latent/LatentSVM.cpp
- src/shogun/machine/LinearLatentMachine.cpp
- src/shogun/machine/LinearMachine.cpp
- src/shogun/machine/LinearMachine.h
- src/shogun/regression/LeastAngleRegression.cpp
- src/shogun/regression/LeastAngleRegression.h
- src/shogun/regression/svr/LibLinearRegression.cpp
- src/shogun/regression/svr/LibLinearRegression.h
- src/shogun/transfer/multitask/LibLinearMTL.cpp
Please take a close look this is dangerous indeed.
The PR is a small step towards tags.
> Use weight vector *only* through getters/setters

- src/shogun/classifier/svm/LibSVM.cpp
- src/shogun/classifier/svm/LibSVM.h
- src/shogun/classifier/svm/LibSVMOneClass.cpp
- src/shogun/classifier/svm/LibSVMOneClass.h
- src/shogun/multiclass/MulticlassLibSVM.cpp
- src/shogun/multiclass/MulticlassLibSVM.h
- src/shogun/multiclass/ScatterSVM.cpp
- src/shogun/multiclass/ScatterSVM.h
- src/shogun/regression/svr/LibSVR.cpp
- src/shogun/regression/svr/LibSVR.h
This patch registers members of LibSVM related classes as parameters or moves them out of the class scope. See #3725.
> LibSVM parameters

- src/shogun/classifier/mkl/MKL.cpp
- src/shogun/classifier/mkl/MKL.h
Registers MKL class parameters and handles 3rd party lib parameters in `::clone()`. See #3725. I couldn't get shogun to compile with CPLEX enabled, it looks to me as if there are plenty of `#ifdef USE_CPLEX...#endif` blocks in shogun that actually don't compile anymore.
> Register parameters for CMKL and override clone()

- src/shogun/labels/Labels.cpp
- src/shogun/labels/Labels.h
Was available in Features, not in Labels. As far as I can tell it's the only interface to figure out if subsets are currently applied.
> Add CLabels::get_subset_stack()

- src/shogun/io/SGIO.cpp
- src/shogun/io/SGIO.h
- tests/unit/io/SGIO_unittest.cc
Unit tests for #3694 plus little changes to SGIO::progress to make unit tests pass.
> Add SGIO::progress unit tests and enhance SGIO::progress

- tests/unit/CMakeLists.txt
Following #3735 serialization tests were not discovered by cmake, I don't think this was the intended behaviour (travis still builds the tests but doesn't run them, see this build https://travis-ci.org/shogun-toolbox/shogun/jobs/213507345#L5782), this should fix it.
> Discover generated serialization tests

- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgBackendViennaCL.h
- src/shogun/mathematics/linalg/LinalgSpecialPurposes.h
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
- tests/unit/mathematics/linalg/operations/Viennacl_operations_unittest.cc
I am going to split the current `LinalgNameSpace` into `SpecialPurpose`, `BasicOps` and `LinearSolver`, while keeping `LinalgNameSpace` as the interface for all, if no one objects.
> LinalgRefacotr - add linalg::logistic

- src/shogun/multiclass/tree/CARTree.cpp
- This fixes the decision tree notebook failing due to assertion in
MeanSquaredError.
- Additional initialization of members in init and minor style fixes.
> Add missing registration of member m_mode in CARTree.

- src/shogun/lib/memory.h
This way sg_memcpy is also defined when TRACE_MEMORY_ALLOCS=OFF.
> Move sg_memcpy out ifdef TRACE_MEMORY_ALLOCS.

- tests/unit/regression/LibSVR_unittest.cc
LibSVM does not work when the kernel cache size is zero.
When use_svmlight is on, CKernel::set_cache_size overwrites the given
size.
> Remove setting kernel cache 0 to fix LibSVR_test failure in nightly_none

- examples/undocumented/libshogun/regression_libsvr.cpp
See also 24e6a24734620abb7275391f839eecd064486d36.
> Remove kernel cache size set to 0 in libshogun libsvr example.

- src/shogun/preprocessor/PCA.cpp
- src/shogun/preprocessor/PCA.h
Small refactoring PR to get to know the project and its processes
> Moving EVD and SVD heavy lifiting into separate methods

- CMakeLists.txt
- src/shogun/lib/config.h.in
Am I missing where this is used?
> Remove HAVE_LARGEFILE conf. option since it is not used.

- .clang-format
- .travis.yml
- scripts/check_format.sh
This PR is focused on make Travis able to evaluate PRs' code style. The main idea is to create a clang-format file which will define some Shogun's code style guidelines. These guidelines should be followed when writing patches/code.
This patch's `.clang-format` file is a bit skinny. There are only some basic instructions which were modelled by looking at this page:
* https://github.com/shogun-toolbox/shogun/wiki/Code-style
A simple example on how Travis will (should) behave after this patch can be found at this link: 
* https://travis-ci.org/geektoni/clang-format-test/jobs/226336339
> Add clang-format file and Travis integration to check PRs' code style.

- src/shogun/lib/cpu.h
This fixes building on all arches; x86 / x86_64 are the only ones, which know about the opcode 'pause'.
> Better support for different and unknown architectures

- doc/readme/INSTALL.md
Delete the line regarding "Shogun in homebrew is outdated", it has been updated 3 days ago to newest version.
> Mac OS install - brew now has latest version

- src/shogun/io/UAIFile.cpp
The unit test _UAIFileTest.preamble_ failed for locales with other decimal delimiters, such as "pt_BR.utf8". Some functions, like strtod(), use the "C" locale and the test failed when they were called with a different one.
This is fixed by using the "C" locale in CUAIFile::get_vector().
> Fix test UAIFileTest.preamble failure for some locales

- doc/readme/INSTALL.md
Following the install docs, I encountered an issue with `brew install shogun` in that the formula wasn't found. A bit of digging into the [homebrew-science](https://github.com/Homebrew/homebrew-science) docs led me to solving this by executing `brew install homebrew/science/shogun`.
> Update install instructions for homebrew

- src/shogun/distributions/Gaussian.cpp
- src/shogun/distributions/Gaussian.h
- src/shogun/features/DataGenerator.cpp
- src/shogun/mathematics/linalg/LinalgNamespace.h
- tests/unit/distribution/MixtureModel_unittest.cc
Those  function names like 'cblas_dger' doesn't make sense to me.
> make guassian get rid of LAPACK

- src/shogun/base/progress.h
- src/shogun/base/range.h
- tests/unit/base/PRange_unittest.cc
- tests/unit/base/Range_unittest.cc
This is a prototype for the new progress bar that will (hopefully) replace `SG_PROGRESS`. This is not a full-fledged solution, it is just to show the idea and to get some feedback about it, so be warned ;)
As @lisitsyn suggested back here #3693, I developed a wrapper that takes a `range()` object and an `SGIO` instance. Every time the iterator is incremented, the wrapper should print a message on screen.
More specifically:
* `PRange` is the wrapper class;
* `PRange<T>::PIterator` is the iterator that will increment the given `Range<T>::Iterator`;
* `ProgressPrinter` is the actual class that will implement the progress bar logic;
The syntax should be something like this:
```c++
for (auto i : progress(range(1, 10), io)) 
{
// Do stuff
}
````
I've thought about more ways to specify a …
> Add PRange class to replace old SG_PROGRESS (WIP)

- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
Operations needed by #3826, linalg + eigen implementation.
~~This is a work in progress: tests, docs, dimension checks etc are missing.~~
PS: if I run `check_format.sh` it wants to rewrite almost completely `LinalgBackendEigen.h`, see https://gist.github.com/micmn/8565fdbb0bcb1e2b1867a934f8f0fbce#file-style-diff-L193
> Add to linalg trace, zero, identity, add_col_vec (CPU only)

- src/shogun/mathematics/linalg/LinalgBackendEigen.h
Eigen 3.3.x casts boolean sum to int, this fix removes add_col_vec for booleans, see #3644 #3656.
> Fix add_col_vec compatibility with eigen 3.3.x

- src/shogun/mathematics/linalg/LinalgBackendEigen.cpp
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgMacros.h
Waiting for the big linalg refactoring, in this way the backend gets compiled only once and compilation time returns to be acceptable , although travis may still fail without splitting the implementation into more files.
> Split Eigen3's linalg backend into header and implementation.

- src/shogun/classifier/AveragedPerceptron.cpp
- src/shogun/classifier/LPBoost.cpp
- src/shogun/classifier/Perceptron.cpp
- src/shogun/classifier/mkl/MKL.cpp
- src/shogun/classifier/mkl/MKLMulticlass.cpp
- src/shogun/classifier/svm/LibLinear.cpp
- src/shogun/classifier/svm/MPDSVM.cpp
- src/shogun/classifier/svm/NewtonSVM.cpp
- src/shogun/classifier/svm/OnlineSVMSGD.cpp
- src/shogun/classifier/svm/SGDQN.cpp
- src/shogun/classifier/svm/SVMLight.cpp
- src/shogun/classifier/svm/SVMSGD.cpp
- src/shogun/classifier/vw/VowpalWabbit.cpp
- src/shogun/features/DotFeatures.cpp
- src/shogun/features/hashed/HashedWDFeaturesTransposed.cpp
- src/shogun/kernel/Kernel.h
- src/shogun/kernel/string/WeightedDegreePositionStringKernel.cpp
- src/shogun/kernel/string/WeightedDegreeStringKernel.cpp
- src/shogun/lib/ShogunException.cpp
- src/shogun/lib/Signal.cpp
- src/shogun/lib/Signal.h
- src/shogun/lib/external/shogun_libsvm.cpp
- src/shogun/machine/KernelMachine.cpp
- src/shogun/multiclass/KNN.cpp
- src/shogun/multiclass/LaRank.cpp
- src/shogun/multiclass/MulticlassLibLinear.cpp
- src/shogun/optimization/liblinear/tron.cpp
- src/shogun/regression/svr/LibLinearRegression.cpp
- src/shogun/transfer/multitask/LibLinearMTL.cpp
- tests/unit/lib/Signal_unittest.cc
This PR <del>should</del> contains the new `CSignal` implementation which will be using RxCpp. <del>However, there are still some things that needs to be addressed (`CSignal::cancel_computation`, there is still Windows code etc.).</del>
> [PrematureStopping] Refactor CSignal class to use RxCpp utilities.

- tests/unit/base/main_unittest.cc
- tests/unit/classifier/svm/SVMOcas_unittest.cc
- tests/unit/environments/LinearTestEnvironment.h
- tests/unit/environments/MultiLabelTestEnvironment.h
- tests/unit/multiclass/MulticlassOCAS_unittest.cc
Previous version used singleton and created useless environment instances in `main()`, also I don't think that you can use that type of singleton with gtest environments since `AddGlobalEnvironment()` frees its memory.
In this patch I used global vars as suggested in gtest guide but of course it could be done differently.
Note: envs should be created after `init_shogun_with_defaults()`? But SVMOcas test fails (rand initialization?)
(+ fix typo in `MutiLabelTestEnvironment`)
> Create test environments in main()

- src/interfaces/csharp_modular/sg_print_functions.cpp
- src/interfaces/java_modular/sg_print_functions.cpp
- src/interfaces/lua_modular/sg_print_functions.cpp
- src/interfaces/modular/SGBase.i
- src/interfaces/octave_modular/sg_print_functions.cpp
- src/interfaces/perl_modular/sg_print_functions.cpp
- src/interfaces/python_modular/sg_print_functions.cpp
- src/interfaces/r_modular/sg_print_functions.cpp
- src/interfaces/ruby_modular/sg_print_functions.cpp
- src/shogun/base/init.cpp
- src/shogun/base/init.h
- src/shogun/machine/Machine.cpp
- src/shogun/machine/Machine.h
- tests/unit/regression/lars_unittest.cc
This will need a rebase when #3853 will get merged.
> [PrematureStopping] Add to CMachine premature stopping methods.

- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- src/shogun/mathematics/linalg/backend/eigen/BasicOps.cpp
- src/shogun/mathematics/linalg/backend/eigen/Decompositions.cpp
- src/shogun/mathematics/linalg/backend/eigen/Misc.cpp
- src/shogun/mathematics/linalg/backend/eigen/Solvers.cpp
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
Needed by #3826 #3842
This includes: add_scalar, center_matrix, eigen_solver, eigen_solver_symmetric, qr_solver, svd, transpose_matrix, triangular_solver.
Some methods (svd, qr, eigen) are not implemented in general fashion but they implement just what is needed by flda, kpca.
~Not merge ready: unit tests missing.~
> Add linalg methods needed by FisherLDA and KernelPCA (CPU-only)

- src/shogun/classifier/LDA.cpp
- src/shogun/classifier/LDA.h
- src/shogun/lib/SGMatrix.cpp
- src/shogun/lib/SGMatrix.h
- src/shogun/lib/SGVector.cpp
- src/shogun/lib/SGVector.h
- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- src/shogun/mathematics/linalg/backend/eigen/BasicOps.cpp
- src/shogun/mathematics/linalg/backend/eigen/Decompositions.cpp
- src/shogun/preprocessor/FisherLDA.cpp
- src/shogun/preprocessor/FisherLDA.h
- tests/unit/lib/SGMatrix_unittest.cc
- tests/unit/lib/SGVector_unittest.cc
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
Starting point to discuss this task. #3482 
Both classes implement two solvers: canonvar (svd based) whose code is very similar in the two implementations except for the regularization parameter in LDA (this PR drops the LDA's solver), and the classic method using covariance matrix, LDA directly computes a solution for the binary classification problem while FisherLDA computes related eigenvectors, so this code isn't strictly _duplicated_ but of course one could use the latter to solve the former with some modification to FisherLDA (i.e. bias computation, but then it should be aware of treating the classification case differently).
A couple of other points:
- LDA supports a regularization parameter in both methods, so FisherLDA should too if we want to use its canonvar solver.
- LDA's …
> Remove duplicate code in LDA/FisherLDA and port the solvers to use linalg (WIP)

- src/shogun/classifier/LDA.cpp
- src/shogun/classifier/LDA.h
- src/shogun/labels/MulticlassLabels.cpp
- src/shogun/labels/MulticlassLabels.h
- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgEnums.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- src/shogun/mathematics/linalg/backend/eigen/Decompositions.cpp
- src/shogun/preprocessor/FisherLDA.cpp
- src/shogun/preprocessor/FisherLDA.h
- src/shogun/solver/LDACanVarSolver.h
- src/shogun/solver/LDASolver.h
- tests/unit/classifier/LDA_unittest.cc
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
This includes:
- refactor LDA binary classification and dimension reduction solvers in two separate classes: `LDASolver`, centers data w.r.t. class, compute within cov matrix (shared by bin. class. and dim. red. llt/eigen solvers); `LDACanVarSolver`, inherits from `LDASolver` and computes the solution through canonical variates algorithm (shared by bin class. and dim. red. canvar solvers)
- fix bias calculation in LDA #3886 
- option to compute SVD by bidiagonalization divide and conquer algorithm (with Eigen >= 3.3)
- MulticlassLabels constructor from BinaryLabels (I know there is already some work going on labels, so let me know if there is a better way)
- LDA benchmarks: https://gist.github.com/micmn/d4b51bf39676621afca563b55bdb9a98 :dancer:
Certainly some docs are missing, I'll double …
> Refactor (Fisher)LDA solvers into separate class

- src/shogun/distance/MahalanobisDistance.cpp
- src/shogun/features/DotFeatures.cpp
- src/shogun/features/DotFeatures.h
Swig doesn't handle mixed static/non-static methods with the same name resulting in the availability of only one of the two.
> Rename static method DotFeatures::get_mean -> compute_mean

- src/shogun/features/DotFeatures.cpp
Would be nice also to parallelize the covariance main loop but is not obvious how to do it properly since  it works on one vector at a time, tried a few variants with openmp but it didn’t improve; the straightforward way to speed-up get_cov would be to compute it by matrix prod (tried, approx. 4X on 4 threads), but this requires the storage of the centered data matrix while the current algorithm doesn’t need that.
> Vectorize DotFeatures covariance/mean calculation

- src/shogun/classifier/AveragedPerceptron.cpp
Once merged FreeBSD build on buildbot should be fine.
> Fix uninitialized memory read in AveragedPerceptron

- src/shogun/features/DotFeatures.cpp
- src/shogun/features/DotFeatures.h
- tests/unit/features/DotFeatures_unittest.cc
@karlnapf 
There are no unit tests for this method, I'll add a few.
Some benchmark (mat-prod 4-thread vs no-copy)
|rows/cols (s)|1000 |2000 |3000 |4000 | 5000|
|---|---|---|---|---|---|
| 1000 | 0.134 / 0.446 | 0.252 / 0.879 | 0.372 / 1.338 | 0.514 / 1.751 | 0.619 / 2.403 |
| 2000 | 0.494 / 2.092 | 0.976 / 4.281 | 1.498 / 6.479 | 1.915 / 8.999 | 2.416 / 10.781 |
| 3000 | 1.107 / 4.726 | 2.149 / 9.414 | 3.426 / 14.347 | 4.343 / 18.773 | 5.363 / 23.466 |
| 4000 | 1.948 / 8.629 | 3.844 / 15.824 | 5.826 / 23.582 | 9.939 / 32.070 | 12.356 / 39.673 |
| 5000 | 4.114 / 12.359 | 8.119 / 25.534 | 11.995 / 45.380 | 16.070 / 49.140 | 19.793 / 65.281 |
> Add option to compute DotFeatures covariance by matrix product

- src/shogun/mathematics/lapack.cpp
- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- src/shogun/mathematics/linalg/backend/eigen/Decompositions.cpp
- src/shogun/mathematics/linalg/backend/eigen/EigenSolvers.cpp
- src/shogun/preprocessor/KernelPCA.cpp
- tests/unit/preprocessor/KernelPCA_unittest.cc
Linag (Eigen):
- set LAPACK's dsyevr as default symmetric eigensolver if available;
- add option to compute only the top-k eigenvalues in symmetric eigensolver;
- split decompositions and eigensolvers implementations.
KernelPCA:
- compute just the needed (top-k) eigenvectors;
- fix sign correctness in unittest.
Fix wrap_dsyevr memory allocation.
> Set LAPACK's dsyevr as default symmetric eigensolver + fixes

- src/shogun/regression/KRRNystrom.cpp
- tests/unit/base/trained_model_serialization_unittest.cc.jinja2
- tests/unit/base/trained_model_serialization_unittest.cc.py
Machines that are failing: CDomainAdaptationSVM, CMKLRegression, CKRRNystrom, CMKLClassification, CMKLOneClass, CSVM, CLibSVMOneClass.
~Most of them should be failing to due custom initialization needed, I'll check if that's the case.~
KRRNystrom was failing due to wrong inizialization, I made a small modification to the solver.
LibSVMOneClass was failing due to serialization inaccuracy, switching to hdf5 format solves it.
The other ones need custom initialization (MKL, DomainAdaptation) and the generic SVM class doesn't implement a solver.
> Add KernelMachines to generated serialization tests

- tests/unit/CMakeLists.txt
> Disable generated serialization tests if HDF5 is not installed

- scripts/check_format.sh
With this #3934 the clang-format script was broken. This patch will fix it.
> Fix clang-format check which was broken.

- NEWS
- doc/readme/INSTALL.md
I wasn't sure where this should go in the list, so I put it at the top. :p  Feel free to move lower if you think it should be lower.
> add note about new conda-forge packages

- src/shogun/labels/MulticlassLabels.cpp
- src/shogun/labels/MulticlassLabels.h
- tests/unit/labels/MulticlassLabels_unittest.cc
- SWIG converted SGMatrix to DoubleMatrix in Java, which conflicted with the MulticlassLabels constructor that used SGVector
> Fix from #3956: Setting multiclass confidence scores in function instead of the constructor

- src/shogun/features/DenseFeatures.cpp
- src/shogun/features/SubsetStack.cpp
Playing around with xval's knn unit test I got segfaults on Subset deallocation, there seems to be two issues:
- `DenseFeatures`  calls `m_subset_stack->remove_all_subsets()` two times, in `free_features()` and in `free_feature_matrix()` that is called from the former;
- SubsetStack's copy ctor doesn't ref `m_active_subset`, but I'm a bit confused about this since every subset is refd by `(CSubset*)other.m_active_subsets_stack->get_element(i);`, so on the contrary I'd expect some memleak...
To reproduce it: https://gist.github.com/micmn/59a41d97d5415b4206eaabf616d26f20
@karlnapf
> Fix SubsetStack copy ctor and dtor memory error

- src/shogun/labels/DenseLabels.cpp
- src/shogun/lib/SGMatrix.cpp
- src/shogun/lib/SGMatrix.h
- src/shogun/multiclass/MCLDA.cpp
- src/shogun/multiclass/QDA.cpp
- src/shogun/multiclass/QDA.h
- tests/unit/base/trained_model_serialization_unittest.cc.jinja2
- tests/unit/base/trained_model_serialization_unittest.cc.py
- tests/unit/lib/SGMatrix_unittest.cc
MulticlassLabels: algorithms set labels by `set_int_label()` that sets only `m_labels` but this way
`m_current_values` is not initialized and hence equals() fails. [not sure how to handle this, zeroed vectors on allocation in DenseLabels for now].
MCLDA: incomplete params registration [fixed].
QDA: incomplete params registration + SGNDArray not serialized [fixed].
MulticlassLibSVM, ScatterSVM: Error: C <= 0, in fact it's set to zero few lines above [??, ignored].
MulticlassTreeGuidedLogisticRegression, CDomainAdaptationMulticlassLibLinear: need custom initialization [ignored].
ShareBoost: apply takes features subset [ignored].
Test store_model_features true/false in kernel machines
Use Some instead of raw pointers in macros
Add SGMatrix::get_submatrix() method
@karlnapf Don't think this …
> Add Multiclass machines to generated serialization tests

- src/shogun/clustering/GMM.cpp
During I'm working on the global random removing, I found we have a lot of plain pointer in GMM. I thought maybe we want this pr, please feel free to close it if it's not. :)
Thank you
> use SGVector instead of plain pointer in GMM

- doc/readme/INSTALL.md
Using home brew without sudo solves the issue of Shogun installation in Mac OS.
> Issue #4001: Updating MacOS installation in INSTALL.md

- cmake/ShogunFindLAPACK.cmake
resolves https://github.com/shogun-toolbox/shogun/issues/3996
When Atlas is not detected, a further check is implemented to see if detected LAPACK API is OpenBLAS using search for an openBLAS specific function. If it is then cblas.h is checked otherwise all LAPACK flags are unset and error is shown.
> detect cblas.h during cmake for openblas

- examples/meta/generator/translate.py
Fixes this bug:
Meta language:
```
Kernel k = kernel("GaussianKernel")
```
Translates to:
```
import numpy as np
from shogun import kernel
k = kernel()
```
i.e. the argument list is not included
> Fix translation bug with static calls

- src/shogun/mathematics/linalg/LinalgBackendViennaCL.h
Should fix the buildbot viennacl failures, like http://buildbot.shogun-toolbox.org:8080/#/builders/6/builds/202
> ViennaCL: fix linalg::element_product() parameters constness

- src/shogun/lib/SGVector.cpp
Same behavior as SGMatrix(rows, cols) [I don't know if it makes sense or this difference is ok and I should call SGVector::zero()].
Should fix DotIterator::add() failing unittest due to non initialized memory.
http://buildbot.shogun-toolbox.org:8080/#/builders/25/builds/158
> Make SGVector(len) 'ctor zero-initialize memory

- examples/meta/csharp/CMakeLists.txt
> Suppress C# unused variable warnings when enable_testing is off

- src/shogun/evaluation/ROCEvaluation.cpp
- src/shogun/evaluation/ROCEvaluation.h
- src/shogun/transfer/multitask/MultitaskROCEvaluation.cpp
ROC evaluation accesses uninitialized memory via CLabel::get_value() instead of the actual labels via CBinaryLabel::get_label().
I added the typecasts after checking the label type and replaced the function calls.
> Fix ROC evaluation to properly access binary labels

- examples/undocumented/libshogun/classifier_mkl_svmlight_modelselection_bug.cpp
Valgrind analysis build fails with: `parser error : xmlSAX2Characters: huge text node` (
http://buildbot.shogun-toolbox.org:8080/#/builders/2/builds/56/steps/9/logs/stdio).
I think that the cause is the script `classifier_mkl_svmlight_modelselection_bug.py`: the log level is set to debug and its outputs ~115MB of text.
I tried running xsltproc on the output file removing that test case (the file goes down to ~5MB) and it generates the html.
> Set classifier_mkl_svmlight_modelselection_bug loglevel to info

- tests/unit/features/iterators/DotIterator_unittest.cc
The unit test was stupidly incorrect (wrong vector size in add(), switched cols and rows number).
Hopefully, after this patch buildbot will stop complaining.
> Fix DotIterator unittest

- src/shogun/base/SGObject.cpp
- src/shogun/base/SGObject.h
- tests/unit/base/SGObject_unittest.cc
Motivation is basic
- No need to replace set -> sets so no need to rename get
- Consistent with Java Map API
> Get/put instead of get/set

- src/shogun/CMakeLists.txt
We use tags to add dependencies such as `#include`. Only headers are to be used here.
@sorig that was causing that segfault of C++ meta_api/calls example! 🤣
> Do not use anything but headers for tags

- examples/meta/src/base_api/kernel.sg
- src/shogun/CMakeLists.txt
- tests/unit/base/trained_model_serialization_unittest.cc.py
I had to remove functions from ctags due to multiple clash of the 'kernel' name. This way it doesn't clash.
> Add an example for creating kernel by its name

- src/shogun/base/class_list.h
- src/shogun/base/progress.h
- src/shogun/classifier/LDA.cpp
- src/shogun/preprocessor/KernelPCA.cpp
- tests/unit/preprocessor/FisherLDA_unittest.cc
- tests/unit/preprocessor/KernelPCA_unittest.cc
- tests/unit/regression/krrnystrom_unittest.cc
This patch fixes some memory leaks discovered by valgrind inside unit tests.
> Memory leaks fixes for unit tests

- src/shogun/evaluation/ROCEvaluation.cpp
Changed the ROC Evaluation messages to the message format
described in the issue.
> Fix Issue #4028: Fix ROC Evaluation Messages

- doc/readme/INTERFACES.md
Did the following things as per #4038 
1) Fixed the lua's example command
2) Fixed R example command's intendation
> Updated example command for lua and R: Fix for issue #4038

- src/interfaces/swig/SGBase.i
Makes it possible to do:
```(python)
import shogun; print shogun.GaussianKernel().has('log_width')
```
> Support std::string wrapping in SWIG

- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- src/shogun/mathematics/linalg/backend/eigen/BasicOps.cpp
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
As mentioned in #4085 by @karlnapf , we need a API in linalg to allow adding a vector to a matrix's diagonal. This PR adds `add_diag_vec` that performs operation `A.diagonal = alpha * A.diagonal + beta * b`. Could you provide some feedback on the API design ?
> Add linalg API to allow adding a vector to diagonal

- src/shogun/features/StringFeatures.cpp
- src/shogun/lib/DynamicObjectArray.h
- tests/unit/base/DynamicObjectArray_unittest.cc
- tests/unit/base/SGObject_unittest.cc
to make `::CSGObject::equals` work
> tag-register raw array

- src/shogun/io/NeuralNetworkFileReader.cpp
- src/shogun/io/SerializableJsonFile.cpp
- src/shogun/io/SerializableJsonReader00.cpp
Replaced depreciated `is_error(ptr)` macro with `ptr == nullptr`.
> Removed is_error macro dependency (#4098)

- src/shogun/base/SGObject.h
- src/shogun/base/class_list.cpp.templ
- tests/unit/base/SGObject_unittest.cc
Add a test that can be used to identify discrepancies between old parameter registration and new tag based registration.
> Test that old parameter names and tag parameter names match

- src/shogun/classifier/mkl/MKL.cpp
- src/shogun/features/PolyFeatures.cpp
- src/shogun/features/SparseFeatures.cpp
- src/shogun/features/SparsePolyFeatures.cpp
- src/shogun/kernel/CombinedKernel.cpp
- src/shogun/kernel/normalizer/DiceKernelNormalizer.h
- src/shogun/kernel/normalizer/SqrtDiagKernelNormalizer.h
- src/shogun/kernel/normalizer/ZeroMeanCenterKernelNormalizer.h
- src/shogun/kernel/string/HistogramWordStringKernel.cpp
- src/shogun/kernel/string/SNPStringKernel.cpp
- src/shogun/kernel/string/SpectrumRBFKernel.cpp
- src/shogun/kernel/string/WeightedCommWordStringKernel.cpp
- src/shogun/kernel/string/WeightedDegreePositionStringKernel.cpp
- src/shogun/kernel/string/WeightedDegreeStringKernel.cpp
- src/shogun/labels/MultilabelLabels.cpp
- src/shogun/lib/DynamicArray.h
- src/shogun/mathematics/linalg/linop/SparseMatrixOperator.cpp
- src/shogun/modelselection/ModelSelectionParameters.cpp
- src/shogun/multiclass/ScatterSVM.cpp
- src/shogun/preprocessor/RandomFourierGaussPreproc.cpp
- src/shogun/transfer/multitask/MultitaskKernelPlifNormalizer.h
Made changes as suggested in #4101 
All tests pass.
> tag-register all raw arrays

- doc/readme/INSTALL.md
The 'git submodule update --init' command works only after changing directory to shogun before actually running the command
> Updated INSTALL.md

- setup.py
The argument in line 127 for `re.compile()` doesn't need `u` flag as the argument has no Unicode letters used. Moreover, this shows as syntax error when run with python3 interpretor.
Removing `u` flag has no adverse consequences on the remaining setup process.
> Correct syntax for compatibilty with python3

- src/shogun/kernel/CombinedKernel.cpp
- src/shogun/kernel/CombinedKernel.h
- tests/unit/kernel/CombinedKernel_unittest.cc
This PR addresses issue #3612, by allowing CombinedKernel init to properly subset CustomKernel subkernels. Hence CustomKernel should now work with mkl / x-validation
Test code used to verify the fix:
```
from shogun import *
from numpy import *
init_shogun_with_defaults()
feats_train=RealFeatures(random.rand(10,10))  
labels=BinaryLabels(array([1,1,1,1,1,-1,-1,-1,-1,-1]))   
kerg = GaussianKernel(2.0)
kerg.init(feats_train,feats_train)
ker1 = CustomKernel(kerg.get_kernel_matrix())
ker2 = GaussianKernel(2.0)
cker = CombinedKernel()
cker.append_kernel(ker1)
cker.append_kernel(ker2)
cft = CombinedFeatures()
cft.append_feature_obj(feats_train)
cft.append_feature_obj(feats_train)
cker.init(cft,cft)
libsvm = LibSVM()
svm = MKLClassification(libsvm) …
```
> Fix issue #3612

- examples/meta/generator/generate.py
- examples/meta/generator/parse.py
- examples/meta/generator/targets/cpp.json
- examples/meta/generator/targets/csharp.json
- examples/meta/generator/targets/java.json
- examples/meta/generator/targets/lua.json
- examples/meta/generator/targets/octave.json
- examples/meta/generator/targets/python.json
- examples/meta/generator/targets/r.json
- examples/meta/generator/targets/ruby.json
- examples/meta/generator/translate.py
- examples/meta/src/meta_api/kwargs.sg
Allows keyword arguments in class constructors and factory functions (when the factory function is called to set the value of a newly initialised variable).
The update in meta-language allows translation of statements like these (meta-language):
```
Kernel k = kernel_machine("SomeKernel", some_parameter=2)
Kernel k2(parameter=500)
```
**A)** To something like this (python)
```
k = kernel_machine("SomeKernel")
k.put("some_parameter", 2)
k2 = Kernel()
k2.put("parameter", 500)
```
**B)** Or something like this (python):
```
k = kernel_machine("SomeKernel", some_parameter=2)
k2 = Kernel(parameter=500)
```
To get A), the `targets/python.json` file should contain:
```
{
...
"Init": {
"Construct": "$name = $typeName($arguments)\n$kwargs",
"Copy": "$name = $expr\n$kwargs",
"KeywordArguments": { …
```
> Extend the meta-language to support keyword arguments

- examples/meta/src/neural_nets/classification_perceptron.sg
Hi! My name is Paco and I'm interested in this project and I would like to get involved with it.
I've created the sample and tested c and python result. They are both the same. 
I'm sending another PR to shogun-data with the integration testing data output of the c++ executable and I'll make a cookbook page then.
> #3555 add meta_example for classifier_perceptron undocumented-sample

- src/shogun/statistical_testing/internals/DataManager.cpp
- src/shogun/statistical_testing/internals/mmd/ComputeMMD.h
- tests/unit/statistical_testing/KernelSelection_unittest.cc
Fixes the bug found by Dmitry as per the SO thread https://stackoverflow.com/questions/48467554/shogun-quadratic-mmd-error-caused-by-varying-train-test-ratio.
> bugfix for train-test ratio in statistical testing

- src/shogun/lib/SGMatrix.cpp
- tests/unit/base/MockObject.h
- tests/unit/base/SGObject_unittest.cc
CSGObject::clone should be fully covered now i.e.
* all parameter combinations that are used in Shogun are cloned in the test
* after clone, object.equals(...) is true
* non-empty objects to make meaningful test
> Replace old clone tests with systematic new one

- cmake/FindMetaExamples.cmake
and clean up obsolete filenames
> make cmake fail if a guarded meta example does not exist

- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- src/shogun/mathematics/linalg/backend/eigen/Decompositions.cpp
- src/shogun/mathematics/linalg/backend/eigen/Solvers.cpp
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
Add LDLT cholesky decomposition and solver for positive semidefinite or negative semidefinite Hermitan matrixes.
See discussion in #4085
> Add LDLT Cholesky decomposition

- examples/meta/generator/targets/ruby.json
- examples/meta/src/meta_api/kwargs.sg
Fixes issue with ruby in #4154
> Switch translation of ruby function calls to allow nested calls

- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- src/shogun/mathematics/linalg/backend/eigen/BasicOps.cpp
There are some methods in linalg using non-const reference for input. This PR add const qualifiers to them.
> Add const qualifier to input of linalg api

- cmake/FindMetaExamples.cmake
- src/shogun/distance/MahalanobisDistance.cpp
- src/shogun/distance/MahalanobisDistance.h
- tests/unit/distance/MahalanobisDistance_unittest.cc
This PR replaces lapack usage with linalg in `MahalanobisDistance`.
A unit test of `MahalanobisDistance` is added (reference computed with Matlab)
> Replace lapack with linalg in MahalanobisDistance

- examples/meta/generator/targets/cpp.json
- examples/meta/generator/targets/csharp.json
- examples/meta/generator/targets/doc.md
- examples/meta/generator/targets/java.json
- examples/meta/generator/targets/lua.json
- examples/meta/generator/targets/octave.json
- examples/meta/generator/targets/python.json
- examples/meta/generator/targets/r.json
- examples/meta/generator/targets/ruby.json
- examples/meta/generator/translate.py
This allows typed getters like `get_real` to be translated to `get<float64_t>` in C++ and `get_real` in the SWIG interfaces.
Note that typed setters (`put`) would be more tricky as we'd have to type the keyword arguments
> Meta examples: add functionality for special translations of certain method calls

- examples/undocumented/libshogun/classifier_libsvm_probabilities.cpp
- examples/undocumented/libshogun/labels_binary_fit_sigmoid.cpp
- src/shogun/evaluation/Calibration.h
- src/shogun/evaluation/SigmoidCalibration.cpp
- src/shogun/evaluation/SigmoidCalibration.h
- src/shogun/labels/MulticlassLabels.cpp
- src/shogun/labels/MulticlassLabels.h
- src/shogun/mathematics/Statistics.cpp
- src/shogun/mathematics/Statistics.h
- tests/unit/evaluation/SigmoidCalibration_unittest.cc
- tests/unit/labels/BinaryLabels_unittest.cc
- tests/unit/mathematics/Statistics_unittest.cc
This PR fixes platt scaling and adds new classes SigmoidCalibration and Calibration. Previously, `fit_sigmoid` was only using the predictions to fit parameters which is incorrect. SigmoidCalibration has been added so that `score_to_probabilites` from `CBinaryLabels` can be removed. This will make the x-validated calibration API cleaner (#4009 ). The old `fit_sigmoid` and `scores_to_probabilities` have still not be removed since they are still needed in multiclass calibration. It would probably be safe to remove them after fixing #4164
> Fix platt scaling

- src/shogun/mathematics/linalg/LinalgBackendBase.h
- src/shogun/mathematics/linalg/LinalgBackendEigen.h
- src/shogun/mathematics/linalg/LinalgBackendViennaCL.h
- src/shogun/mathematics/linalg/LinalgNamespace.h
- src/shogun/mathematics/linalg/backend/eigen/BasicOps.cpp
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
- tests/unit/mathematics/linalg/operations/Viennacl_operations_unittest.cc
Add transpose flags to arguments of `linalg::element_prod`
```
void element_prod(const SGMatrix<T>& A, const SGMatrix<T>& B, SGMatrix<T>& result,
bool transpose_A = false, bool transpose_B = false)
```
This makes `element_prod` have a consistent interface as `matrix_prod`
> Add transpose flags to element_prod

- src/shogun/distributions/EMMixtureModel.cpp
- src/shogun/distributions/Gaussian.cpp
- src/shogun/distributions/Histogram.cpp
- src/shogun/distributions/KernelDensity.h
- src/shogun/distributions/MixtureModel.cpp
- src/shogun/distributions/PositionalPWM.cpp
- src/shogun/distributions/classical/GaussianDistribution.cpp
- src/shogun/distributions/classical/GaussianDistribution.h
- src/shogun/mathematics/Math.h
- src/shogun/mathematics/Random.cpp
- src/shogun/mathematics/Statistics.cpp
- src/shogun/neuralnets/DeepBeliefNetwork.cpp
- src/shogun/neuralnets/NeuralSoftmaxLayer.cpp
- src/shogun/neuralnets/RBM.cpp
#4186  replacing ```CMath::log``` with ```std::log``` at a few places
> drop CMath log 

- src/shogun/mathematics/linalg/LinalgNamespace.h
- src/shogun/metric/LMNN.cpp
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
* Add method that computes trace of the product of two matrixes in linalg
* Use `trace_dot` in LMNN
> Add trace_dot in linalg

- src/shogun/lib/Signal.cpp
- src/shogun/lib/Signal.h
- tests/unit/lib/Signal_unittest.cc
> Fix issue #4201.

- src/shogun/features/DataGenerator.cpp
- src/shogun/features/StringFeatures.cpp
- src/shogun/lib/JLCoverTree.h
- src/shogun/mathematics/Math.h
- src/shogun/mathematics/ajd/FFDiag.cpp
- src/shogun/preprocessor/DecompressString.cpp
- src/shogun/regression/KRRNystrom.cpp
- src/shogun/structure/DynProg.cpp
- src/shogun/structure/TwoStateModel.cpp
- tests/unit/mathematics/Math_unittest.cc
Refer #4186 .
- Replaced `CMtah::ceil` with `std::ceil` in all files.
> Replace CMath::ceil with std::ceil

- src/shogun/machine/gp/KLDualInferenceMethod.cpp
- src/shogun/mathematics/Math.cpp
- src/shogun/mathematics/Math.h
- src/shogun/modelselection/GradientModelSelection.cpp
- src/shogun/optimization/lbfgs/LBFGSMinimizer.cpp
- src/shogun/optimization/lbfgs/lbfgs.cpp
- tests/unit/mathematics/Math_unittest.cc
- tests/unit/mathematics/Statistics_unittest.cc
Fix issue #4186, drop CMath::is_infinity. 
Replace CMath::is_infinity with std::isinf and delete the function is_infinity in CMath.
> Fix issue #4186, replace CMath::is_infinity with std::isinf

- examples/undocumented/python/mathematics_logdet.py
- src/shogun/base/class_list.h
- src/shogun/labels/BinaryLabels.cpp
- src/shogun/labels/DenseLabels.cpp
- src/shogun/labels/DenseLabels.h
- src/shogun/labels/Labels.cpp
- src/shogun/labels/MulticlassLabels.cpp
- src/shogun/machine/Machine.h
- src/shogun/mathematics/linalg/ratapprox/logdet/LogDetEstimator.cpp
- src/shogun/mathematics/linalg/ratapprox/logdet/LogDetEstimator.h
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.cpp
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.h
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/LogRationalApproximationCGM.cpp
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/LogRationalApproximationCGM.h
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/LogRationalApproximationIndividual.cpp
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/LogRationalApproximationIndividual.h
- src/shogun/mathematics/linalg/ratapprox/opfunc/OperatorFunction.h
- src/shogun/mathematics/linalg/ratapprox/opfunc/RationalApproximation.cpp
- src/shogun/mathematics/linalg/ratapprox/opfunc/RationalApproximation.h
- src/shogun/multiclass/tree/CARTree.cpp
- tests/unit/mathematics/linalg/DenseMatrixExactLog_unittest.cc
- tests/unit/mathematics/linalg/LogDetEstimator_unittest.cc
- tests/unit/mathematics/linalg/RationalApproximation_unittest.cc
#4074 #4092 
[WIP]
This is part 1 here we will refactor code to change the use of the computation classes to be deleted.
Part 2 will including deleting the classes.
I am struggling with ```RationalApproximation``` unit test.
Please review this and guide me further.
> Refactoring

- src/shogun/neuralnets/RBM.cpp
add progress bar to RBM algorithm
> add progress bar to RBM fix #3889

- tests/unit/classifier/svm/LibLinear_unittest.cc
> Refactored the CLibLinear test codes and reduced them from 1300 lines to 470.

- src/shogun/classifier/GaussianProcessClassification.cpp
- src/shogun/evaluation/StructuredAccuracy.cpp
- src/shogun/machine/GaussianProcessMachine.cpp
- src/shogun/machine/LinearLatentMachine.cpp
- src/shogun/machine/gp/ExactInferenceMethod.cpp
- src/shogun/machine/gp/FITCInferenceMethod.cpp
- src/shogun/machine/gp/SingleFITCLaplaceInferenceMethod.cpp
- src/shogun/machine/gp/SingleLaplaceInferenceMethod.cpp
- src/shogun/machine/gp/VarDTCInferenceMethod.cpp
- src/shogun/regression/GaussianProcessRegression.cpp
- src/shogun/structure/FactorGraphDataGenerator.cpp
- src/shogun/structure/FactorGraphModel.cpp
- src/shogun/structure/HMSVMModel.cpp
- src/shogun/structure/HashedMultilabelModel.cpp
- src/shogun/structure/HierarchicalMultilabelModel.cpp
- src/shogun/structure/MulticlassModel.cpp
- src/shogun/structure/MulticlassSOLabels.cpp
- src/shogun/structure/MultilabelCLRModel.cpp
- src/shogun/structure/MultilabelModel.cpp
- src/shogun/structure/MultilabelSOLabels.cpp
- tests/unit/distribution/MixtureModel_unittest.cc
- tests/unit/labels/StructuredLabels_unittest.cc
- tests/unit/structure/DualLibQPBMSOSVM_unittest.cc
- tests/unit/structure/HashedMultilabelModel_unittest.cc
- tests/unit/structure/HierarchicalMultilabelModel_unittest.cc
- tests/unit/structure/MultilabelCLRModel_unittest.cc
- tests/unit/structure/MultilabelModel_unittest.cc
- tests/unit/structure/MultilabelSOLabels_unittest.cc
Refer #4191 
This is partial wok. There are more cases that need to be re-factored.
PS The build is expected to fail terribly when interface options are set. This is because `build/src/interfaces/{language}/shogun{language}wrap.cxx` needs refactoring wherever `obtain_from_generic` is used.
> Replace obtain_from_generic with .as

- examples/meta/src/base_api/put_get.sg
- src/shogun/multiclass/KNN.cpp
Quite minor. Also opening to test the change in Travis.
> Minor fix of knn's parameter naming for consistency.

- src/shogun/converter/ica/FastICA.cpp
add progress bar to FastICA algorithm.
> add progress bar to FastICA

- tests/unit/distribution/MixtureModel_unittest.cc
The fix was a bit unexpected. The test failed often with *segfault* locally. Valgrind showed it was at unref.
After applying the fix, tested locally that valgrind is happy and the test passed always after running a bunch of times.
The test is a bit bad nonetheless since it relies on magic numbers. But hopefully this will turn it green.
> Some-ize Gaussian Mixture model UT. Closes #4241 (luckily).

- examples/meta/src/binary/linear_discriminant_analysis.sg
- src/shogun/classifier/LDA.cpp
- src/shogun/labels/MulticlassLabels.cpp
- tests/unit/classifier/LDA_unittest.cc
```lda.get_real("m_gamma")``` did not work due to this casting of gamma(float) as int
> factory methods in lda meta example #4247

- examples/meta/src/base_api/put_get_add.sg
- examples/meta/src/binary/averaged_perceptron.sg
- examples/meta/src/binary/linear_support_vector_machine.sg
- examples/meta/src/binary/perceptron.sg
- examples/meta/src/multiclass/ecoc_random.sg
- examples/meta/src/multiclass/linear.sg
- examples/meta/src/multiclass/linear_discriminant_analysis.sg
- examples/meta/src/multiclass/logistic_regression.sg
- examples/meta/src/multiclass/quadratic_discriminant_analysis.sg
- examples/meta/src/multiclass/shareboost.sg
- examples/meta/src/regression/least_angle_regression.sg
- examples/undocumented/libshogun/classifier_lda.cpp
- src/shogun/classifier/AveragedPerceptron.cpp
- src/shogun/classifier/Perceptron.cpp
- src/shogun/classifier/svm/LibLinear.cpp
- src/shogun/evaluation/MulticlassAccuracy.cpp
- src/shogun/machine/MulticlassMachine.cpp
- src/shogun/multiclass/ShareBoost.cpp
- src/shogun/multiclass/ShareBoostOptimizer.cpp
- src/shogun/multiclass/tree/C45ClassifierTree.cpp
- src/shogun/multiclass/tree/ID3ClassifierTree.cpp
- src/shogun/regression/LeastAngleRegression.cpp
- tests/unit/multiclass/MulticlassOCAS_unittest.cc
- tests/unit/multiclass/tree/C45ClassifierTree_unittest.cc
- tests/unit/multiclass/tree/ID3ClassifierTree_unittest.cc
In preparation to drop manual dynamic dispatching in put
This PR is a set of minor API example refactoring changes
> more refactoring of API examples and required c++ adjustments

- src/shogun/mathematics/linalg/linsolver/CGMShiftedFamilySolver.cpp
- src/shogun/mathematics/linalg/linsolver/CGMShiftedFamilySolver.h
- src/shogun/mathematics/linalg/linsolver/IterativeShiftedLinearFamilySolver.cpp
- src/shogun/mathematics/linalg/linsolver/IterativeShiftedLinearFamilySolver.h
- src/shogun/mathematics/linalg/ratapprox/logdet/LogDetEstimator.cpp
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.cpp
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/DenseMatrixExactLog.h
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/LogRationalApproximationCGM.cpp
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/LogRationalApproximationCGM.h
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/LogRationalApproximationIndividual.cpp
- src/shogun/mathematics/linalg/ratapprox/logdet/opfunc/LogRationalApproximationIndividual.h
- src/shogun/mathematics/linalg/ratapprox/opfunc/OperatorFunction.h
- src/shogun/mathematics/linalg/ratapprox/opfunc/RationalApproximation.h
This is [WIP]
In #4103 we decided to use something like 
```#pragma omp parallel for reduction(+:samples[:num_estimates])``` 
but this is not working because openmp does not support vector reduction in this manner.
I declared a custom reduction for vector type which did the trick. However, I found this similar problem solved [here](https://github.com/shogun-toolbox/shogun/blob/c8c66e61ebc8b6e90cbe726df7557c7291310cab/src/shogun/kernel/Kernel.cpp#L1139) using a critical section.
> parrallel computation of sample in LogDetEstimator

- src/shogun/lib/StoppableSGObject.cpp
- src/shogun/lib/StoppableSGObject.h
- src/shogun/machine/Machine.cpp
- tests/unit/lib/StoppableSGObject_unittest.cc
@karlnapf @shubham808 
This PR contains the first implementation of the new `cancel_computation` method. It is still a WIP so any comments on it are appreciated. Please see the unit test to see the new behaviour.
> Improve cancel_computation to enable testing.

- src/shogun/machine/KernelMachine.cpp
- src/shogun/machine/KernelMachine.h
- src/shogun/machine/LinearMachine.cpp
- src/shogun/machine/Machine.cpp
- src/shogun/machine/Machine.h
> connect Kernel and Linear machine to a signal handler

- examples/meta/generator/translate.py
> Use set in dependency string in meta translator

- src/interfaces/swig/SGBase.i
- src/shogun/io/SGIO.cpp
- src/shogun/io/SGIO.h
- tests/unit/io/SGIO_unittest.cc
* separate formatting and printing in SGIO::message
* define new macros `REQUIRE_E`, `SG_THROW`, `SG_STHROW` that support using custom exception types
> Allow SGIO to throw custom exception types

- doc/cookbook/source/examples/pipeline/pipeline.rst
- doc/cookbook/source/index.rst
- examples/meta/src/pipeline/pipeline.sg
- src/interfaces/swig/Machine.i
- src/interfaces/swig/factory.i
- src/shogun/util/factory.h
* add pipeline meta example and cookbook
* add transformer factory
> Add pipeline cookbook

- examples/undocumented/python/features_dense.py
- examples/undocumented/python/features_dense_byte.py
- examples/undocumented/python/features_dense_longint.py
- examples/undocumented/python/features_dense_real.py
- src/shogun/classifier/NearestCentroid.cpp
- src/shogun/features/CombinedFeatures.cpp
- src/shogun/features/CombinedFeatures.h
- src/shogun/features/DenseFeatures.cpp
- src/shogun/features/DenseFeatures.h
- src/shogun/features/Features.h
- src/shogun/preprocessor/DimensionReductionPreprocessor.cpp
- tests/unit/features/DenseFeatures_unittest.cc
* methods made const: `create_merged_copy`, `get_feature_matrix`, `get_feature_obj`
* dropped public methods: `set_feature_vector`, `reshape`, `steal_feature_matrix`
* made `free_features` protected
> Cleanup non-const methods in dense and combined features

- src/shogun/lib/exception/NotFittedException.h
- src/shogun/preprocessor/KernelPCA.cpp
- src/shogun/preprocessor/KernelPCA.h
- src/shogun/preprocessor/NormOne.cpp
- src/shogun/preprocessor/PCA.cpp
- src/shogun/preprocessor/PCA.h
- src/shogun/preprocessor/PruneVarSubMean.cpp
- src/shogun/preprocessor/PruneVarSubMean.h
- src/shogun/preprocessor/RescaleFeatures.cpp
- src/shogun/preprocessor/RescaleFeatures.h
- src/shogun/transformer/Transformer.cpp
- src/shogun/transformer/Transformer.h
- tests/unit/preprocessor/NormOne_unittest.cc
* Use linalg in NormOne
* Optimize PruneVarSubMean
> Cleanup and optimize transformers

- src/shogun/CMakeLists.txt
- tests/unit/base/trained_model_serialization_test.cc.py
@micmn we added mixins which makes the base class checking a bit more complicated.
mixins are defined as `template <class T> CIterativeMachine : public T { ... }`, and the `class Perceptron : public CIterativeMachine<CLinearMachine> { ... }`, so ctags will generate `inherits: CIterativeMachine` and therefore the perceptron would not be included in the tests.
We cannot use your mapping function instead because I dont know what type of machine will lie inside, e.g. `'CiterativeMachine: CMachine'` would not work for example for kernel machines.
So what I did here is to extract the mixin template parameter from the declaration of the class and then substitute the base class with that, but keep the mixin in the `classes` dictionary (we might want to define tests for mixins only later on).
> Make trained model testing support single mixins

- src/shogun/util/factory.h
add another string features factory that calls `obtain_from_char` internally to translate a string features to high order representation
> Add factory of embed string features

- examples/undocumented/python/modelselection_grid_search_kernel.py
- src/interfaces/python/DenseFeatures_protocols.i
- src/shogun/clustering/KMeans.cpp
- src/shogun/features/DenseFeatures.h
- src/shogun/kernel/AUCKernel.cpp
- src/shogun/metric/LMNNImpl.cpp
- src/shogun/preprocessor/KernelPCA.cpp
- src/shogun/preprocessor/KernelPCA.h
- tests/unit/kernel/PeriodicKernel_unittest.cc
now the only usage of `set_feature_matrix` is swig https://github.com/shogun-toolbox/shogun/blob/770f748f4fd3b6db66ac08e699924f7152a8557d/src/interfaces/python/DenseFeatures_protocols.i#L661
after that we can drop it from public api
> Drop usage of set_feature_matrix

- CMakeLists.txt
- examples/meta/CMakeLists.txt
As explained in #4408 switching execution order defines Cmake variables properly
> Meta examples generation bug fix (fixes #4408)

- src/shogun/base/AnyParameter.h
- src/shogun/base/SGObject.h
- src/shogun/lib/bitmask_operators.h
This PR refactors the AnyParameterProperties class to use a mask (`m_mask_attribute`) to store parameter options:
* HYPERPARAMETER: the parameter determines how the training is performed, e.g. regularisation
* GRADIENT_PARAM: the parameter is used in gradient updates
* MODEL_PARAM: model parameter that is trained, e.g. weight and bias
This makes the use of Enums in `AnyParameter.h` not necessary anymore, and the corresponding getter methods can be replaced with `bool` return type.  
The mask uses bit shift operations to keep information in a hexadecimal representation.
> AnyParameterProperties refactor

- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
Refactored all the linalg Eigen3 operations in `Eigen3_operations_unittest.cc` as suggested in #4383.
In addtion to typed testing, changes include:
* Decreased tolerance for `float` type tests to work with `float32_t`, `float64_t` and `floatmax_t`
* Different values in tests where the same code has to work with both `int` and `float` types
I did not add `complex128_t`, `bool` or `char` tests at this point.
I just need help writing a test for `SGMatrix_squared_error` as this potentially requires changing CMath::pow (mentioned in #4383). At this point I left the original test.
I know it's quite a large number of lines changed in one PR, but this is mainly a code refactor and the tests are almost identical.
All tests run fine locally!
> Refactored linalg operations tests ( addresses #4383)

- src/shogun/classifier/Perceptron.cpp
- src/shogun/classifier/svm/NewtonSVM.cpp
- src/shogun/machine/IterativeMachine.h
- tests/unit/classifier/NewtonSVM_unittest.cc
- tests/unit/classifier/Perceptron_unittest.cc
Tests that train 3 models:
1. Complete train till convergence
2. Train with max number of iteration set low at x
3. Train a model then prematurely stop it at x iterations, the continue training till convergence
The results are compared to ensure proper state update in every iteration.
Eventually we would want this done automatically for all Iterative Machines.
> iterative machine unit test

- tests/unit/neuralnets/NeuralLeakyRectifiedLinearLayer_unittest.cc
- tests/unit/neuralnets/NeuralLinearLayer_unittest.cc
- tests/unit/neuralnets/NeuralLogisticLayer_unittest.cc
1. Replaced redundancies using fixture class and its helper methods.
2. Replaced manual for loops with shogun::linalg calls wherever feasible.
> Fix remaining Neural Layer Tests

- src/shogun/lib/type_case.h
This PR fixes a bug where creating maps in the header file was causing undefined behaviour. The `static` keyword guarantees that the maps are allocated only once. The `const` should allow the compiler to optimise it a bit more.
> Static initialisation of maps

- src/shogun/base/AnyParameter.h
This fixes issues with the copy constructor. Bugs probably only occurred when compiling in Debug mode (see #4439).
> Fixed uninitialised attributes in AnyParameterProperties

- src/shogun/lib/type_case.h
Doxygen doesn't seem to like arguments packs and variadic templates and gives an error in these lines of shogun_doxygen.i:
```
// File: structshogun_1_1type__internal_1_1function__traits_3_01Ret_07F_1_1_5_08_07Args_8_8_8_08_01const_01_4.xml
%feature("docstring") shogun::type_internal::function_traits<
Ret(F::*)(Args...) const > " "; --> ***this line causes an issue****
```
and
```
%feature("docstring") shogun::Types< T1, Args... > " ";
```
This PR tells doxygen to ignore the corresponding C++ code.
> Fixes doxygen issue

- examples/meta/generator/targets/python.json
- examples/undocumented/python/preprocessor_fisherlda.py
- examples/undocumented/python/structure_multiclass_bmrm.py
- src/interfaces/swig/SGBase.i
- src/interfaces/swig/shogun.i
Found this [thread](https://github.com/swig/swig/issues/723) where they discuss how to add a Python method (written in python) dynamically even when using swig's -builtins. The python code then checks which CSGObject getter works and returns the one that works. If the parameter does not exist it returns the same `RuntimeError` as we would get with the other getters.
I tested this with Python 3.6, but it should work fine with any other Python 3 version, and should work with Python 2.7.
> single get method for python interface

- src/interfaces/python/swig_typemaps.i
- src/interfaces/swig/SGBase.i
SystemError seems to be the default error in the rest of the SWIG files so makes sense to switch it here. (See also https://github.com/shogun-toolbox/shogun/pull/4441#discussion_r247320333)
> Python API change RuntimeError to SystemError

- src/interfaces/python/swig_typemaps.i
- src/shogun/base/Version.cpp
- src/shogun/base/Version.h
Also made stuff in Version constexpr, because nothing stops it from being constexpr I think? 
@vigsterkr in your C++17 branch can you check if you can remove the cpp definition of the constexpr members, i.e. `constexpr int64_t Version::version_revision` and so on? In C++17 constexpr implies inline and variables can be inline :D
And then can now get shogun version from python, which is useful for openml.
```python
import shogun as sg
sg.__version__
```
> Shogun version python

- src/interfaces/python/swig_typemaps.i
- src/interfaces/swig/SGBase.i
- src/shogun/base/SGObject.cpp
- src/shogun/base/SGObject.h
- tests/unit/base/SGObjectAll_unittest.cc
This PR exposes AnyParameter map to the C++ library, which is hidden in Self in CSGObject. This is done with ~~`std::reference_wrapper<const AnyParameter>`~~ `std::shared_ptr<const AnyParameter>` (which should make it impossible to mess with a model's parameters through the getter?).
It then further extends the Python API to have parameter_name and parameter_type getters. These can be useful to debug from Python.
> Expose AnyParameter map to C++ API and extend in SWIG

- src/shogun/base/Version.cpp
- src/shogun/base/Version.h
This reverts commit 46f7838f3c0815e821a3bd0b8805e152e26e9da7.
due to constexpr after every commit the Version.h will change and thus
the whole ccache is contaminated as Version.h is included in SGObject.h
> Revert "constexpr version"

- src/shogun/kernel/GaussianKernel.cpp
- src/shogun/kernel/GaussianKernel.h
as none of the children classes overrides it.
here's the difference in number of operations (top with virtual and none inlined bottom non-virtual inlined) when compiled with O3:
https://pastebin.com/1LvR1338
> GaussianKernel set/get_width should be non-virutal

- src/shogun/features/FeatureTypes.h
- src/shogun/io/TBOutputFormat.cpp
- src/shogun/lib/sg_types.h
- src/shogun/lib/type_case.h
- tests/unit/base/SGObject_unittest.cc
- tests/unit/io/TBOutputFormat_unittest.cc
- tests/unit/lib/DynamicArray_unittest.cc
- tests/unit/lib/SGSparseVector_unittest.cc
- tests/unit/lib/SGTypes_unittest.cc
- tests/unit/lib/type_case_unittest.cc
- tests/unit/machine/FeatureDispatchCRTP_unittest.cc
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
- tests/unit/sg_gtest_utilities.h
In shogun we redefine types so many it makes sense to start centralising definitions of types. An example is the Google typed tests where we redefine what types to test against. 
I also replaced all the current TYPED_TEST_CASE with a SG_TYPED_TEST_CASE macro that does the conversions from shogun to gtest.
> Centralise type definitions

- src/shogun/lib/SGVector.h
- tests/unit/lib/SGVector_unittest.cc
There is an incorrect call of std::copy algorithm in SGVector.h:132 file. The code on specified line clears original data and return wrong result.
To solve this problem the  correct call to coping algorithm is added.
Unit test for SGVector::as function updated to check error case.
> Fix issue with an incorrect data coping in SGVector class #4497

- src/interfaces/swig/SGBase.i
- src/shogun/base/SGObject.cpp
- src/shogun/base/SGObject.h
Added a no throw overload of SGObject::get(const std::string&) to use in swig. Catching errors in C++ code in swig can cause issues because of the error printing.
The interface method is needed for openml to check if a model parameter is an sgobject, i.e. CKernel or CDistance, and if so it needs to be serialised properly.
> Check if parameter is sg base

- doc/cookbook/source/references.bib
- doc/cookbook/source/static/mathconf.js
- doc/cookbook/source/static/shogun-style.css
- doc/cookbook/source/templates/layout.html
- doc/cookbook/source/templates/page.html
- doc/readme/INSTALL.md
- doc/readme/INTERFACES.md
- doc/readme/MISSION.md
These commits address issues reported in #4512.
Apart from updating links, one notable change is the style of the reference section in the example pages. Please see the effect below.
> Cleanup broken links and fix some issues on Shogun's webpages.

- doc/readme/INTERFACES.md
- examples/meta/generator/parse.py
- examples/meta/generator/targets/cpp.json
- examples/meta/generator/targets/csharp.json
- examples/meta/generator/targets/java.json
- examples/meta/generator/targets/octave.json
- examples/meta/generator/targets/python.json
- examples/meta/generator/translate.py
- examples/meta/src/features/string_char.sg
- examples/undocumented/python/features_string_char.py
- examples/undocumented/python/features_string_file.py
- examples/undocumented/python/features_string_ulong.py
- examples/undocumented/python/features_string_word.py
- src/interfaces/csharp/swig_typemaps.i
- src/interfaces/java/swig_typemaps.i
- src/interfaces/octave/swig_typemaps.i
- src/interfaces/python/swig_typemaps.i
- src/interfaces/swig/shogun.i
- src/shogun/features/StringFeatures.cpp
- src/shogun/features/StringFeatures.h
- src/shogun/lib/SGStringList.cpp
- src/shogun/lib/SGStringList.h
- src/shogun/preprocessor/StringPreprocessor.cpp
- src/shogun/util/factory.h
- tests/unit/features/StringFeatures_unittest.cc
- tests/unit/utils/factory_unittest.cc
A simple meta example for CStringFeatures<char>. 
I would like to make changes and add output file for an integration test but I am not sure if the current outputs are enough for that. Currently, it stores "max_string_length", "number_of_strings" and "length_of_first_string". I don't think that is possible to practically check all the values of "strings". 
However, if you don't have a better idea I could add eight variables that store the value of the first vector before and after the change to "test".
> Add meta example features-char-string

- examples/meta/generator/translate.py
- src/interfaces/csharp/swig_typemaps.i
- src/interfaces/swig/Library.i
- src/shogun/io/Serializable.h
- src/shogun/lib/DynamicObjectArray.h
Implicitly tests all in/out typemaps for string lists via the string_char meta example
> Add string lists to integration testing

- .ci/windows-steps.yml
- cmake/ShogunFindLAPACK.cmake
This fixes the blas header issue in the windows CI. There seems to be an issue with the include directories if not specified. This PR explicitly gives the path to the MKL libraries to Cmake which then can find the blas header file.
> Use MKL in windows build

- src/shogun/mathematics/linalg/LinalgNamespace.h
- tests/unit/mathematics/linalg/operations/Eigen3_operations_unittest.cc
Moving average is implemented in the form average_n = (1-alpha)*average_{n-1} + alpha*x. This has an additional multiplication compared to average_n = average_{n-1} + alpha*(x-average_n), but it should has less rounding error when alpha is small (not sure).
> Add cumulative moving average function

- src/shogun/mathematics/eigen3.h
- tests/unit/mathematics/Integration_unittest.cc
This PR addresses the issue with complex.h interfering with the codebase. The header is included by lapacke, which is included by eigen3.h.
> Fix complex/lapack bug

- examples/meta/src/binary/linear_support_vector_machine.sg
- examples/meta/src/evaluation/cross_validation.sg
- examples/meta/src/evaluation/cross_validation_support_vector_machine.sg
- examples/meta/src/meta_api/enums.sg
- examples/undocumented/python/classifier_multiclass_ecoc.py
- examples/undocumented/python/modelselection_grid_search_liblinear.py
- examples/undocumented/python/modelselection_random_search_liblinear.py
- src/interfaces/swig/Classifier.i
- src/interfaces/swig/Classifier_includes.i
now that @gf712 implemented a nice solutions for enum options in #4537 , we can start removing more classes, such as LibLinear
> remove LibLinear from SWIG

- .gitignore
- examples/meta/src/gaussian_process/regression.sg
- examples/meta/src/gaussian_process/sparse_regression.sg
- src/shogun/base/AnyParameter.h
- src/shogun/base/SGObject.cpp
- src/shogun/features/DenseFeatures.cpp
- src/shogun/kernel/Kernel.cpp
@karlnapf Is this what you had in mind?
> Read only property

- CMakeLists.txt
- src/shogun/lib/GPUMatrix.cpp
- src/shogun/lib/GPUMatrix.h
- src/shogun/lib/config.h.in
- tests/unit/base/Some_unittest.cc
- tests/unit/kernel/ShiftInvariantKernel_unittest.cc
- tests/unit/lib/GPUMatrix_unittest.cc
- tests/unit/mathematics/linalg/DenseMatrixOperator_unittest.cc
- tests/unit/regression/lars_unittest.cc
Drop HAVE_CXX11 macro. Some fix for #4284 on gpl submodule has been submitted [there](https://github.com/shogun-toolbox/shogun-gpl/pull/9).
> Drop HAVE_CXX11 macro, fix for #4284

- src/shogun/regression/svr/LibLinearRegression.cpp
This PR addresses the issue #4561. The problem was an uninitialized variable, so it created unpredictable behaviour.
> Fix liblinear regression bug

- src/shogun/regression/svr/LibLinearRegression.cpp
- tests/unit/regression/LibLinearRegression_unittest.cc
Sklearn and liblinear use `m_tube_epsilon=0.1` as default, so I used this as the default value
> Fix parameter registration in liblinear regression

- src/shogun/lib/type_case.h
- tests/unit/lib/type_case_unittest.cc
This is needed to raise compile time error when passing a constant as a non const reference to lambda.
This works when any is const:
```
auto lambda = [](auto const& val) {}
auto lambda = [](auto val) {}
```
This [should] fail when any is const
```
auto lambda = [](auto& val) {}
```
The latter does not cause a compile time error and leads to unexpected behaviour at runtime
> fix return type of lambda

- examples/meta/generator/translate.py
- examples/meta/src/evaluation/cross_validation_multiple_kernel_learning_weights_storage.sg
There seems to be an issue with the recursive lookup of keywords in the program dictionary during translation. The lookup stops when it finds a keyword, but should instead continue as there may be more nested keywords of interest.
Example:
```
Machine svm = machine("...", svm=as_svm(libsvm))
```
Old behaviour ignores the `as_svm` globalCall, which causes it not to add `as_svm` import.
> Translator doesn't find method calls within method calls

- examples/meta/src/regression/multiple_kernel_learning.sg
- examples/undocumented/python/evaluation_cross_validation_mkl_weight_storage.py
- src/interfaces/swig/factory.i
- src/shogun/base/class_list.h
- src/shogun/clustering/KMeansMiniBatch.cpp
- src/shogun/converter/ica/FFSep.cpp
- src/shogun/converter/ica/ICAConverter.cpp
- src/shogun/converter/ica/Jade.cpp
- src/shogun/kernel/GaussianKernel.cpp
- src/shogun/kernel/Kernel.cpp
- src/shogun/machine/GaussianProcessMachine.cpp
- src/shogun/machine/Pipeline.cpp
- src/shogun/multiclass/ShareBoost.cpp
- src/shogun/preprocessor/DensePreprocessor.cpp
- src/shogun/regression/GaussianProcessRegression.cpp
- src/shogun/solver/LDASolver.h
- src/shogun/util/factory.h
- tests/unit/clustering/kmeans_unittest.cc
- tests/unit/kernel/CombinedKernel_unittest.cc
- tests/unit/regression/GaussianProcessRegression_unittest.cc
> factories are factories

- src/shogun/base/SGObject.cpp
- src/shogun/base/SGObject.h
- src/shogun/io/SGIO.h
- src/shogun/lib/exception/ShogunException.cpp
- src/shogun/lib/exception/ShogunException.h
Fixes two things:
- SGObject::get noexcept version calling a function that throws an error 
- ShogunException c++11 compliance (which requires exceptions to be nothrow copy constructible)
see https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR60-CPP.+Exception+objects+must+be+nothrow+copy+constructible
> Exception fix

- src/shogun/util/converters.h
`std::isfinite` in msvc only accepts floats (otherwise there is an `ambiguous call to overloaded function` compiler error), so need to use `_isfinite` from cfloat to implicitly covert non-floats to floats.
> isfinite for msvc

- src/shogun/classifier/AveragedPerceptron.cpp
- src/shogun/classifier/Perceptron.cpp
@karlnapf This is how it would look like with the current design. (Related to #4590)
> Make classifiers observable.

- src/shogun/lib/type_case.h
there were issues with automatic type deduction of sgvector and sgmatrix when they were being used inside the custom lambda
> fixes issue with auto type deduction for containers

- examples/undocumented/libshogun/evaluation_cross_validation_mkl_weight_storage.cpp
- src/shogun/base/SGObject.cpp
- src/shogun/base/SGObject.h
- src/shogun/base/base_types.h
- src/shogun/classifier/Perceptron.cpp
- src/shogun/evaluation/CrossValidation.cpp
- src/shogun/evaluation/CrossValidationStorage.cpp
- src/shogun/lib/observers/ParameterObserver.cpp
- src/shogun/lib/observers/ParameterObserver.h
- src/shogun/lib/observers/ParameterObserverCV.cpp
- src/shogun/lib/observers/ParameterObserverCV.h
- src/shogun/lib/observers/ParameterObserverHistogram.cpp
- src/shogun/lib/observers/ParameterObserverHistogram.h
- src/shogun/lib/observers/ParameterObserverLogger.cpp
- src/shogun/lib/observers/ParameterObserverLogger.h
- src/shogun/lib/observers/ParameterObserverScalar.cpp
- src/shogun/lib/observers/ParameterObserverScalar.h
- src/shogun/lib/observers/ParameterObserverTensorBoard.cpp
- src/shogun/modelselection/GradientModelSelection.cpp
- src/shogun/modelselection/GridSearchModelSelection.cpp
- src/shogun/modelselection/RandomSearchModelSelection.cpp
- tests/unit/base/SGObject_unittest.cc
- tests/unit/lib/observers/ParameterObserverCV_unittest.cc
- tests/unit/lib/observers/ParameterObserverScalar_unittest.cc
* Prepend a C in front of concrete ParameterObserver classes;
* Fix printing inside ParameterObserverLogger;
> Fix observers for the interfaces.

- src/shogun/base/SGObject.h
- src/shogun/base/base_types.h
- src/shogun/lib/type_case.h
- src/shogun/util/clone.h
- tests/unit/base/MockObject.h
* Fix `observe()` method when called for `SGVector`/`SGMatrix`. The given `SGVector/SGMatrix` was not cloned correctly (since copying them just copy the pointer to the raw data and it does not make a clone of the data itself).
<del>I moved some useful type traits from `type_case.h` to `base_types.h` since I did not want to pollute too much `SGObject.h` with unnecessary headers. </del>
Any comments on this change? @karlnapf @vigsterkr @gf712
> Fix observe() method when called for SGVector/SGMatrix.

- src/interfaces/python/CustomKernel_protocols.i
- src/interfaces/python/DenseFeatures_protocols.i
- src/interfaces/python/DenseLabels_protocols.i
- src/interfaces/python/SGVector_protocols.i
The `PySequenceMethods.sq_item` and `PyMappingMethods.mp_subscript` functions/PyObject* in shogun are not conforming to the format `PyObject*(PyObject *o, Py_ssize_t i)` (they are `PyObject*(PyObject *o, Py_ssize_t I, bool)`). 
This causes a compilation error in SWIG 4.0.0, for example:
```
shogunPYTHON_wrap.cxx:812720:5: error: cannot initialize a member subobject of type 'binaryfunc' (aka '_object *(*)(_object *, _object *)') with an lvalue of type 'PyObject *(PyObject *, PyObject *, bool)' (aka '_object *(_object *, _object *, bool)'): different number of parameters (2 vs 3)
CustomKernel_getsubscript,                /* mp_subscript */
```
This PR hides the 3 argument implementation from python and exposes a function with 2 args that calls the 3 args version.
> fixes swig 4.0.0 compilation error

- src/shogun/kernel/normalizer/AvgDiagKernelNormalizer.h
- src/shogun/kernel/normalizer/DiceKernelNormalizer.h
- src/shogun/kernel/normalizer/FirstElementKernelNormalizer.h
- src/shogun/kernel/normalizer/IdentityKernelNormalizer.h
- src/shogun/kernel/normalizer/KernelNormalizer.h
- src/shogun/kernel/normalizer/RidgeKernelNormalizer.h
- src/shogun/kernel/normalizer/ScatterKernelNormalizer.h
- src/shogun/kernel/normalizer/SqrtDiagKernelNormalizer.h
- src/shogun/kernel/normalizer/TanimotoKernelNormalizer.h
- src/shogun/kernel/normalizer/VarianceKernelNormalizer.h
- src/shogun/kernel/normalizer/ZeroMeanCenterKernelNormalizer.h
- src/shogun/transfer/multitask/MultitaskKernelMaskNormalizer.h
- src/shogun/transfer/multitask/MultitaskKernelMaskPairNormalizer.h
- src/shogun/transfer/multitask/MultitaskKernelMklNormalizer.h
- src/shogun/transfer/multitask/MultitaskKernelNormalizer.h
- src/shogun/transfer/multitask/MultitaskKernelPlifNormalizer.h
- src/shogun/transfer/multitask/MultitaskKernelTreeNormalizer.h
This makes the kernel normalizer interface constant, which will be useful when attempting to make the kernel interface stateless. It also changes accessibility of `alloc_and_compute_diag` in some normalizers from public to protected, since it's only a helper function used in initialization.
> Make kernel normalizer functions const

- .ci/ci.yml
- .ci/macos-steps.yml
- src/shogun/CMakeLists.txt
The problem is that mkl tries to run in parallel mode without proper openmp available. I found that these options solve the problem:
1. Install openmp and link to it (which is what I did here)
2. Tell mkl programatically to run in sequential mode if openmp is not available (not the best solution, since it wasn't designed to solve linking problems. `mkl_rt` should solve those).
3. Don't use the dynamic signle library `mkl_rt` and link to each single library needed (`mkl_core`, etc.), and use the sequential library `mkl_sequential`.
> Fix MKL macOS bug

- src/shogun/base/AnyParameter.h
We always call the `AnyParameter` ctor with a temporary `Any`, so we might as well just move it in the ctor instead of copying.
> Move Any in AnyParameter ctor

- examples/meta/src/clustering/gaussian_mixture_models.sg
- examples/meta/src/observers/gaussian_mixture_models.sg
- src/shogun/base/SGObject.cpp
- src/shogun/base/SGObject.h
- src/shogun/base/base_types.h
- src/shogun/classifier/LDA.cpp
- src/shogun/clustering/GMM.cpp
- src/shogun/evaluation/CrossValidationStorage.cpp
- src/shogun/evaluation/CrossValidationStorage.h
- src/shogun/lib/observers/ParameterObserverCV.cpp
- src/shogun/regression/LeastAngleRegression.cpp
- src/shogun/regression/LeastAngleRegression.h
- src/shogun/util/clone.h
* Emit log-likelihood, alphas and gaussians when using the `train_em()` method;
* Emit log-likelihood, alphas and gaussians when using the `train_smem()` method;
* Change m_coefficients registered name to "coefficients" and fix meta example;
> Make GMM model observable.

- examples/meta/CMakeLists.txt
The meta examples are built only once now (just when they are modified).
> Fix meta examples build process.

- tests/unit/base/trained_model_serialization_test.cc.py
@vigsterkr  this should fix the encoding issue for python2
> allow users to compile shogun with python2

- src/interfaces/python/swig_typemaps.i
swig 4.0 imports everything from _shogun.so in shogun.py, rather than the package:
```python
from _shogun import *
```
instead of
```python
import _shogun
```
> swig 4.0 python file imports everything

- src/shogun/lib/SGMatrix.cpp
- src/shogun/lib/SGMatrix.h
- src/shogun/lib/SGVector.cpp
- src/shogun/lib/SGVector.h
- src/shogun/multiclass/QDA.cpp
- tests/unit/lib/SGMatrix_unittest.cc
- tests/unit/lib/SGVector_unittest.cc
This will be useful for replacing raw pointers. A slice can be reference counted, and we keep track of an offset, which is needed in deallocation.
Why this is useful?
When we want to do an operation with only a part of a vector. For example
```C++
float64_t CCombinedDotFeatures::dense_dot(int32_t vec_idx1, const float64_t* vec2, int32_t vec2_len) const
{
float64_t result=0;
uint32_t offs=0;
for (index_t f_idx=0; f_idx<get_num_feature_obj(); f_idx++)
{
CDotFeatures* f = get_feature_obj(f_idx);
int32_t dim = f->get_dim_feature_space();
result += f->dense_dot(vec_idx1, vec2+offs, dim)*f->get_combined_feature_weight();
offs += dim;
SG_UNREF(f);
}
return result;
}
```
Where we do a dot product with `vec2 + offs`. Without slicing, we would have to create a new SGVector that points to `vec2 + …
> Implement SGVector slicing

- doc/OpenCV_docs/OpenCV_KNN_vs_Shogun_KNN.md
- doc/OpenCV_docs/OpenCV_NN_vs_Shogun_NN.md
- doc/OpenCV_docs/OpenCV_SVM_vs_Shogun_SVM.md
- examples/undocumented/libshogun/mathematics_lapack.cpp
- src/shogun/classifier/svm/NewtonSVM.cpp
- src/shogun/lib/OpenCV/CV2SGFactory.h
- src/shogun/lib/SGMatrix.cpp
- src/shogun/lib/SGMatrix.h
- src/shogun/lib/SGVector.cpp
- src/shogun/lib/SGVector.h
- src/shogun/lib/memory.h
- src/shogun/mathematics/Statistics.cpp
- tests/unit/mathematics/Statistics_unittest.cc
- tests/unit/mathematics/linalg/NormalSampler_unittest.cc
@vigsterkr I made SG_ALIGNED_MALLOC reduce to SG_MALLOC if aligned malloc is not available, so as to not repeat the macroed if statement. But now SG_CALLOC is turned to aligned malloc followed by std::fill, so I'm not sure.
> Use aligned malloc for SGVector and SGMatrix allocation

- src/shogun/base/AnyParameter.h
- src/shogun/base/SGObject.cpp
- src/shogun/base/SGObject.h
- src/shogun/base/composition.h
- src/shogun/base/constraint.h
- src/shogun/clustering/KMeansBase.cpp
- tests/unit/base/MockObject.h
- tests/unit/base/SGObject_unittest.cc
Here is a design I came up with to constrain parameter values. At compile time we know the constraints so it can all be wrapped into a tuple that is "evaluated" and should be inlined properly at O3. The issue is the casting from any to the respective type, which is expensive, but then we can "ignore" the parameter type and have something like this:
```cpp
SG_ADD(&k, "k", "k, the number of clusters",
ParameterProperties::HYPER | ParameterProperties::CONSTRAIN,
SG_CONSTRAINT(positive<>()));
```
and then python
```python
In [1]: import shogun as sg                                                                                                                                                                                 
In [2]: kmeans = sg.machine("KMeans") …
```
> Constrain parameter values

- src/shogun/base/SGObject.h
- src/shogun/features/DenseFeatures.cpp
- src/shogun/features/Features.cpp
@theartful @karlnapf this is how you could set the bitmask values for all parameters added via SG_ADD.
The issue is that there are also the watch_param methods... I think we really need the replacement from SG_ADD macro to a variadic method in SGObject, so we can add all this logic in one place.
> option to set default parameter bitmask value

- src/interfaces/swig/Distribution.i
- src/interfaces/swig/Features.i
- src/interfaces/swig/Machine.i
- src/interfaces/swig/Multiclass.i
- src/interfaces/swig/RandomMixin.i
- src/interfaces/swig/SGBase.i
- src/interfaces/swig/Statistics.i
- src/interfaces/swig/Structure.i
- src/shogun/evaluation/CrossValidation.cpp
- src/shogun/evaluation/CrossValidation.h
- src/shogun/mathematics/RandomMixin.h
- src/shogun/mathematics/Seedable.h
This has the artifact that if a parent class has the Seedable mixin, a derived class can't have RandomMixin (seed will be registered twice). It can be solved using SFINAE
```
RandomMixin : public Parent (if parent has Seedable)
RandomMixin : public Seedable<Parent> (if parent doesn't have Seedable)
```
but I'm not sure it's worth it, as it would complicate swig.
> Split RandomMixin into prng and seed classes
